import { PrismaClient } from '@prisma/client';
import * as bcrypt from 'bcrypt';

const prisma = new PrismaClient();

async function main() {
  console.log('ðŸŒ± Sembrando datos de prueba...');

  const passwordHash = await bcrypt.hash('Admin123!', 10);
  const passwordHashDemo = await bcrypt.hash('Demo123!', 10);

  // â”€â”€â”€ USUARIOS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  const admin = await prisma.usuarios.upsert({
    where: { email: 'admin@agrodata.com' },
    update: {},
    create: {
      nombre: 'Administrador',
      email: 'admin@agrodata.com',
      password: passwordHash,
      rol: 'ADMIN',
      activo: true,
    },
  });

  const usuario1 = await prisma.usuarios.upsert({
    where: { email: 'carlos.mendoza@agrodata.com' },
    update: {},
    create: {
      nombre: 'Carlos Mendoza',
      email: 'carlos.mendoza@agrodata.com',
      password: passwordHashDemo,
      rol: 'USER',
      activo: true,
    },
  });

  const usuario2 = await prisma.usuarios.upsert({
    where: { email: 'maria.garcia@agrodata.com' },
    update: {},
    create: {
      nombre: 'MarÃ­a GarcÃ­a',
      email: 'maria.garcia@agrodata.com',
      password: passwordHashDemo,
      rol: 'USER',
      activo: true,
    },
  });

  console.log('âœ… Usuarios creados');

  // â”€â”€â”€ PRODUCTORES â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  const productoresData = [
    {
      codigo: 'SOC-001',
      dni: '45123678',
      nombres: 'TeÃ³filo',
      apellido_paterno: 'Huanca',
      apellido_materno: 'Quispe',
      sexo: 'MASCULINO' as const,
      fecha_nacimiento: new Date('1975-03-15'),
      estado_civil: 'CASADO' as const,
      telefono: '951234567',
      correo: 'teofilo.huanca@gmail.com',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      comunidad: 'San Juan de Bolognesi',
      direccion: 'Jr. Los Andes 456',
      nivel_educativo: 'SECUNDARIA' as const,
      idioma_principal: 'QUECHUA' as const,
      idioma_secundario: 'NINGUNO' as const,
      material_vivienda: 'Adobe',
      acceso_agua: 'SI',
      acceso_energia: 'NO',
      acceso_internet: 'NO',
      seguro_salud: 'ESSALUD',
      acceso_credito: 'SI',
      servicio_sanitario: 'LETRINA',
      estado: 'ACTIVO' as const,
      activo: true,
      fecha_ingreso: new Date('2020-01-15'),
      organizacion: 'Cooperativa Agraria San Juan',
      cargo: 'SOCIO' as const,
      created_by: admin.id,
    },
    {
      codigo: 'SOC-002',
      dni: '46234567',
      nombres: 'Juana',
      apellido_paterno: 'Mamani',
      apellido_materno: 'Condori',
      sexo: 'FEMENINO' as const,
      fecha_nacimiento: new Date('1980-07-22'),
      estado_civil: 'CASADO' as const,
      telefono: '952345678',
      correo: 'juana.mamani@hotmail.com',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      comunidad: 'Pampa Cangallo',
      direccion: 'Calle Primavera 123',
      nivel_educativo: 'PRIMARIA' as const,
      idioma_principal: 'QUECHUA' as const,
      idioma_secundario: 'ESPANOL' as const,
      estado: 'ACTIVO' as const,
      activo: true,
      fecha_ingreso: new Date('2020-02-10'),
      organizacion: 'Cooperativa Agraria San Juan',
      cargo: 'VICEPRESIDENTE' as const,
      created_by: admin.id,
    },
    {
      codigo: 'SOC-003',
      dni: '47345678',
      nombres: 'Miguel',
      apellido_paterno: 'Ticona',
      apellido_materno: 'Yupanqui',
      sexo: 'MASCULINO' as const,
      fecha_nacimiento: new Date('1968-11-05'),
      estado_civil: 'CASADO' as const,
      telefono: '953456789',
      correo: null,
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Vinchos',
      comunidad: 'Huallhua',
      direccion: 'Sin direcciÃ³n',
      nivel_educativo: 'SIN_ESTUDIOS' as const,
      idioma_principal: 'QUECHUA' as const,
      idioma_secundario: 'NINGUNO' as const,
      estado: 'ACTIVO' as const,
      activo: true,
      fecha_ingreso: new Date('2020-01-15'),
      organizacion: 'Cooperativa Agraria San Juan',
      cargo: 'SOCIO' as const,
      created_by: admin.id,
    },
    {
      codigo: 'SOC-004',
      dni: '48456789',
      nombres: 'Rosa',
      apellido_paterno: 'Ccallpa',
      apellido_materno: 'Mendoza',
      sexo: 'FEMENINO' as const,
      fecha_nacimiento: new Date('1985-04-18'),
      estado_civil: 'CONVIVIENTE' as const,
      telefono: '954567890',
      correo: 'rosa.ccallpa@gmail.com',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      comunidad: 'San Juan de Bolognesi',
      direccion: 'Av. Progreso 789',
      nivel_educativo: 'TECNICO' as const,
      idioma_principal: 'ESPANOL' as const,
      idioma_secundario: 'QUECHUA' as const,
      estado: 'ACTIVO' as const,
      activo: true,
      fecha_ingreso: new Date('2021-03-20'),
      organizacion: 'Cooperativa Agraria San Juan',
      cargo: 'TESORERO' as const,
      created_by: admin.id,
    },
    {
      codigo: 'SOC-005',
      dni: '49567890',
      nombres: 'Valeriano',
      apellido_paterno: 'Quispe',
      apellido_materno: 'Huanca',
      sexo: 'MASCULINO' as const,
      fecha_nacimiento: new Date('1972-09-30'),
      estado_civil: 'VIUDO' as const,
      telefono: '955678901',
      correo: null,
      departamento: 'Ayacucho',
      provincia: 'Cangallo',
      distrito: 'Cangallo',
      comunidad: 'Chuschi',
      direccion: 'Campamento s/n',
      nivel_educativo: 'PRIMARIA' as const,
      idioma_principal: 'QUECHUA' as const,
      idioma_secundario: 'ESPANOL' as const,
      estado: 'ACTIVO' as const,
      activo: true,
      fecha_ingreso: new Date('2020-05-01'),
      organizacion: 'Cooperativa Agraria San Juan',
      cargo: 'SECRETARIO' as const,
      created_by: admin.id,
    },
    {
      codigo: 'SOC-006',
      dni: '41678901',
      nouns: 'Elena',
      apellido_paterno: 'Soto',
      apellido_materno: 'Ramos',
      sexo: 'FEMENINO' as const,
      fecha_nacimiento: new Date('1990-01-12'),
      estado_civil: 'SOLTERO' as const,
      telefono: '956789012',
      correo: 'elena.soto@outlook.com',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Carmen Alto',
      comunidad: 'Carmen Alto',
      direccion: 'Jr. San MartÃ­n 321',
      nivel_educativo: 'UNIVERSITARIO' as const,
      idioma_principal: 'ESPANOL' as const,
      idioma_secundario: 'QUECHUA' as const,
      estado: 'ACTIVO' as const,
      activo: true,
      fecha_ingreso: new Date('2022-06-15'),
      organizacion: 'Cooperativa Agraria San Juan',
      cargo: 'VOCAL' as const,
      created_by: admin.id,
    },
    {
      codigo: 'SOC-007',
      dni: '42789012',
      nombres: 'Fortunato',
      apellido_paterno: 'Lipa',
      apellido_materno: 'Ccorahua',
      sexo: 'MASCULINO' as const,
      fecha_nacimiento: new Date('1965-06-25'),
      estado_civil: 'CASADO' as const,
      telefono: '957890123',
      correo: null,
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      comunidad: 'Pillcuaro',
      direccion: 'Sin direcciÃ³n',
      nivel_educativo: 'PRIMARIA' as const,
      idioma_principal: 'QUECHUA' as const,
      idioma_secundario: 'NINGUNO' as const,
      estado: 'ACTIVO' as const,
      activo: true,
      fecha_ingreso: new Date('2020-01-15'),
      organizacion: 'Cooperativa Agraria San Juan',
      cargo: 'SOCIO' as const,
      created_by: admin.id,
    },
    {
      codigo: 'SOC-008',
      dni: '43890123',
      nombres: 'Cristina',
      apellido_paterno: 'Huaman',
      apellido_materno: 'Poma',
      sexo: 'FEMENINO' as const,
      fecha_nacimiento: new Date('1978-12-08'),
      estado_civil: 'CASADO' as const,
      telefono: '958901234',
      correo: 'cristina.huaman@gmail.com',
      departamento: 'Ayacucho',
      provincia: 'Cangallo',
      distrito: 'Los Chankas',
      comunidad: 'Tambo',
      direccion: 'Av. Libertad 567',
      nivel_educativo: 'SECUNDARIA' as const,
      idioma_principal: 'ESPANOL' as const,
      idioma_secundario: 'QUECHUA' as const,
      estado: 'ACTIVO' as const,
      activo: true,
      fecha_ingreso: new Date('2021-07-01'),
      organizacion: 'Cooperativa Agraria San Juan',
      cargo: 'SOCIO' as const,
      created_by: admin.id,
    },
    {
      codigo: 'SOC-009',
      dni: '44901234',
      nombres: 'Bernardo',
      apellido_paterno: 'Ccahuana',
      apellido_materno: 'Zea',
      sexo: 'MASCULINO' as const,
      fecha_nacimiento: new Date('1982-02-14'),
      estado_civil: 'CASADO' as const,
      telefono: '959012345',
      correo: null,
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Vinchos',
      comunidad: 'San Lorenzo de Quinti',
      direccion: 'Calle Los Olivos 890',
      nivel_educativo: 'SECUNDARIA' as const,
      idioma_principal: 'QUECHUA' as const,
      idioma_secundario: 'ESPANOL' as const,
      estado: 'INACTIVO' as const,
      activo: false,
      fecha_ingreso: new Date('2020-08-10'),
      organizacion: 'Cooperativa Agraria San Juan',
      cargo: 'SOCIO' as const,
      created_by: admin.id,
    },
    {
      codigo: 'SOC-010',
      dni: '45012345',
      nombres: 'Luisa',
      apellido_paterno: 'Palomino',
      apellido_materno: 'Garcia',
      sexo: 'FEMENINO' as const,
      fecha_nacimiento: new Date('1995-08-20'),
      estado_civil: 'SOLTERO' as const,
      telefono: '960123456',
      correo: 'luisa.palomino@yahoo.com',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      comunidad: 'San Juan de Bolognesi',
      direccion: 'Jr. Comercio 234',
      nivel_educativo: 'UNIVERSITARIO' as const,
      idioma_principal: 'ESPANOL' as const,
      idioma_secundario: 'NINGUNO' as const,
      estado: 'SUSPENDIDO' as const,
      activo: true,
      fecha_ingreso: new Date('2023-01-10'),
      organizacion: 'Cooperativa Agraria San Juan',
      cargo: 'SOCIO' as const,
      created_by: admin.id,
    },
    {
      codigo: 'SOC-011',
      dni: '46123456',
      nombres: 'Epifanio',
      apellido_paterno: 'Ynga',
      apellido_materno: 'Ttito',
      sexo: 'MASCULINO' as const,
      fecha_nacimiento: new Date('1970-05-03'),
      estado_civil: 'CASADO' as const,
      telefono: '961234567',
      correo: null,
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      comunidad: 'Pampa Cangallo',
      direccion: 'Sin direcciÃ³n',
      nivel_educativo: 'PRIMARIA' as const,
      idioma_principal: 'QUECHUA' as const,
      idioma_secundario: 'ESPANOL' as const,
      estado: 'ACTIVO' as const,
      activo: true,
      fecha_ingreso: new Date('2020-03-05'),
      organizacion: 'Cooperativa Agraria San Juan',
      cargo: 'SOCIO' as const,
      created_by: admin.id,
    },
    {
      codigo: 'SOC-012',
      dni: '47234567',
      nouns: 'Catalina',
      apellido_paterno: 'Chavez',
      apellido_materno: 'Alarcon',
      sexo: 'FEMENINO' as const,
      fecha_nacimiento: new Date('1988-10-17'),
      estado_civil: 'CASADO' as const,
      telefono: '962345678',
      correo: 'catalina.chavez@gmail.com',
      departamento: 'Ayacucho',
      provincia: 'Cangallo',
      distrito: 'Cangallo',
      comunidad: 'Chuschi',
      direccion: 'Calle San Juan 654',
      nivel_educativo: 'TECNICO' as const,
      idioma_principal: 'ESPANOL' as const,
      idioma_secundario: 'QUECHUA' as const,
      estado: 'ACTIVO' as const,
      activo: true,
      fecha_ingreso: new Date('2022-04-12'),
      organizacion: 'Cooperativa Agraria San Juan',
      cargo: 'SOCIO' as const,
      created_by: admin.id,
    },
  ];

  // Fix fields that had typos
  const cleanedData = productoresData.map((p) => {
    const clean = { ...p };
    if ('nouns' in clean) {
      (clean as any).nombres = (clean as any).nouns;
      delete (clean as any).nouns;
    }
    return clean;
  });

  const productores = [];
  for (const data of cleanedData) {
    const p = await prisma.productor.upsert({
      where: { dni: data.dni },
      update: {},
      create: data as any,
    });
    productores.push(p);
  }

  console.log(`âœ… ${productores.length} productores creados`);

  // â”€â”€â”€ FAMILIARES â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  const familiaresData = [
    { productor_id: productores[0].id, nombres: 'Mercedes Quispe de Huanca', parentesco: 'Esposa', dni: '45123679', sexo: 'FEMENINO' as const, fecha_nacimiento: new Date('1978-05-20'), ocupacion: 'Agricultora', dependiente: false, vive_con_productor: true },
    { productor_id: productores[0].id, nombres: 'Jhonatan Huanca Quispe', parentesco: 'Hijo', sexo: 'MASCULINO' as const, fecha_nacimiento: new Date('2000-08-10'), ocupacion: 'Estudiante', nivel_educativo: 'SECUNDARIA' as const, dependiente: true, vive_con_productor: true },
    { productor_id: productores[0].id, nombres: 'Katherin Huanca Quispe', parentesco: 'Hija', sexo: 'FEMENINO' as const, fecha_nacimiento: new Date('2004-03-25'), ocupacion: 'Estudiante', nivel_educativo: 'SECUNDARIA' as const, dependiente: true, vive_con_productor: true },
    { productor_id: productores[1].id, nombres: 'Alejandro Mamani Condori', parentesco: 'Esposo', dni: '46234568', sexo: 'MASCULINO' as const, fecha_nacimiento: new Date('1978-09-12'), ocupacion: 'Agricultor', dependiente: false, vive_con_productor: true },
    { productor_id: productores[1].id, nombres: 'Soledad Mamani Mamani', parentesco: 'Hija', sexo: 'FEMENINO' as const, fecha_nacimiento: new Date('2002-12-01'), ocupacion: 'Agricultora', dependiente: true, vive_con_productor: true },
    { productor_id: productores[2].id, nombres: 'Rufina Yupanqui de Ticona', parentesco: 'Esposa', dni: '47345679', sexo: 'FEMENINO' as const, fecha_nacimiento: new Date('1970-07-15'), ocupacion: 'Agricultora', dependiente: false, vive_con_productor: true },
    { productor_id: productores[2].id, nombres: 'Brian Ticona Yupanqui', parentesco: 'Hijo', sexo: 'MASCULINO' as const, fecha_nacimiento: new Date('1998-02-28'), ocupacion: 'Agricultor', dependiente: false, vive_con_productor: false },
    { productor_id: productores[4].id, nombres: 'Gladys Yupanqui de Quispe', parentesco: 'Esposa', sexo: 'FEMENINO' as const, fecha_nacimiento: new Date('1975-11-10'), ocupacion: 'Agricultora', dependiente: false, vive_con_productor: true },
    { productor_id: productores[4].id, nombres: 'Yerson Quispe Yupanqui', parentesco: 'Hijo', sexo: 'MASCULINO' as const, fecha_nacimiento: new Date('2001-06-18'), ocupacion: 'Estudiante', nivel_educativo: 'TECNICO' as const, dependiente: true, vive_con_productor: true },
    { productor_id: productores[6].id, nombres: 'Gregoria Ccorahua de Lipa', parentesco: 'Esposa', sexo: 'FEMENINO' as const, fecha_nacimiento: new Date('1968-04-22'), ocupacion: 'Agricultora', dependiente: false, vive_con_productor: true },
    { productor_id: productores[7].id, nombres: 'Mario Huaman Poma', parentesco: 'Esposo', dni: '43890124', sexo: 'MASCULINO' as const, fecha_nacimiento: new Date('1976-03-30'), ocupacion: 'Agricultor', dependiente: false, vive_con_productor: true },
    { productor_id: productores[10].id, nombres: 'Gladys Ttito de Ynga', parentesco: 'Esposa', sexo: 'FEMENINO' as const, fecha_nacimiento: new Date('1973-08-05'), ocupacion: 'Agricultora', dependiente: false, vive_con_productor: true },
  ];

  const cleanedFamiliares = familiaresData.map((f) => {
    const clean = { ...f };
    if ('nouns' in clean) {
      (clean as any).nombres = (clean as any).nouns;
      delete (clean as any).nouns;
    }
    return clean;
  });

  for (const f of cleanedFamiliares) {
    await prisma.familiar.create({ data: f as any });
  }

  console.log(`âœ… ${cleanedFamiliares.length} familiares creados`);

  // â”€â”€â”€ PARCELAS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  const parcelasData = [
    // Productor 1 - TeÃ³filo Huanca (Presidente) - 3 parcelas
    {
      productor_id: productores[0].id,
      codigo: 'PAR-001',
      nombre: 'San Juan Alto',
      cultivo: 'Quinua',
      area: 5.50,
      area_certificada: 5.50,
      area_unidad: 'ha',
      ubicacion: 'San Juan de Bolognesi, Acos Vinchos',
      comunidad: 'San Juan de Bolognesi',
      sector: 'Alto',
      altitud: '3800',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      latitud: '-13.0850',
      longitud: '-74.4520',
      precision_gps: '5m',
      tipo_suelo: 'Franco arcilloso',
      textura: 'Media',
      pendiente: '15-25%',
      fuente_agua: 'Manantial',
      sistema_riego: 'SequÃ­a',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Media',
      certificacion: 'ORGANICA' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    {
      productor_id: productores[0].id,
      codigo: 'PAR-002',
      nombre: 'San Juan Bajo',
      cultivo: 'Papa Nativa',
      area: 3.20,
      area_certificada: 3.20,
      area_unidad: 'ha',
      ubicacion: 'San Juan de Bolognesi, Acos Vinchos',
      comunidad: 'San Juan de Bolognesi',
      sector: 'Bajo',
      altitud: '3600',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      latitud: '-13.0920',
      longitud: '-74.4480',
      precision_gps: '3m',
      tipo_suelo: 'Franco arenoso',
      textura: 'Media',
      pendiente: '5-15%',
      fuente_agua: 'RÃ­o',
      sistema_riego: 'A gravedad',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Alta',
      certificacion: 'ORGANICA' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    {
      productor_id: productores[0].id,
      codigo: 'PAR-003',
      nombre: 'Pampa Redonda',
      cultivo: 'Cebada',
      area: 2.00,
      area_certificada: null,
      area_unidad: 'ha',
      ubicacion: 'San Juan de Bolognesi, Acos Vinchos',
      comunidad: 'San Juan de Bolognesi',
      sector: 'Pampa',
      altitud: '3500',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      latitud: '-13.0980',
      longitud: '-74.4390',
      precision_gps: '5m',
      tipo_suelo: 'Arcilloso',
      textura: 'Fina',
      pendiente: '0-5%',
      fuente_agua: 'Lluvia',
      sistema_riego: 'SequÃ­a',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Baja',
      certificacion: 'EN_TRANSICION' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    // Productor 2 - Juana Mamani (Vicepresidenta) - 2 parcelas
    {
      productor_id: productores[1].id,
      codigo: 'PAR-004',
      nombre: 'Pampa Cangallo Grande',
      cultivo: 'Quinua',
      area: 8.00,
      area_certificada: 8.00,
      area_unidad: 'ha',
      ubicacion: 'Pampa Cangallo, Acos Vinchos',
      comunidad: 'Pampa Cangallo',
      sector: 'Central',
      altitud: '3400',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      latitud: '-13.1050',
      longitud: '-74.4200',
      precision_gps: '3m',
      tipo_suelo: 'Franco limoso',
      textura: 'Media',
      pendiente: '5-15%',
      fuente_agua: 'RÃ­o',
      sistema_riego: 'A gravedad',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Alta',
      certificacion: 'ORGANICA' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    {
      productor_id: productores[1].id,
      codigo: 'PAR-005',
      nombre: 'Pampa Chica',
      cultivo: 'Tarwi',
      area: 2.50,
      area_certificada: null,
      area_unidad: 'ha',
      ubicacion: 'Pampa Cangallo, Acos Vinchos',
      comunidad: 'Pampa Cangallo',
      sector: 'Norte',
      altitud: '3350',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      latitud: '-13.1000',
      longitud: '-74.4150',
      precision_gps: '5m',
      tipo_suelo: 'Franco arcilloso',
      textura: 'Media',
      pendiente: '15-25%',
      fuente_agua: 'Lluvia',
      sistema_riego: 'SequÃ­a',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Baja',
      certificacion: 'CONVENCIONAL' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    // Productor 3 - Miguel Ticona - 2 parcelas
    {
      productor_id: productores[2].id,
      codigo: 'PAR-006',
      nombre: 'Huallhua Superior',
      cultivo: 'Quinua',
      area: 4.00,
      area_certificada: 4.00,
      area_unidad: 'ha',
      ubicacion: 'Huallhua, Vinchos',
      comunidad: 'Huallhua',
      sector: 'Alto',
      altitud: '3900',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Vinchos',
      latitud: '-13.1200',
      longitud: '-74.3800',
      precision_gps: '5m',
      tipo_suelo: 'Franco arenoso',
      textura: 'Media',
      pendiente: '15-25%',
      fuente_agua: 'Manantial',
      sistema_riego: 'SequÃ­a',
      zona_agroecologica: 'SunÃ­',
      disponibilidad_agua: 'Media',
      certificacion: 'ORGANICA' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    {
      productor_id: productores[2].id,
      codigo: 'PAR-007',
      nombre: 'Huallhua Inferior',
      cultivo: 'Frijol',
      area: 1.80,
      area_certificada: null,
      area_unidad: 'ha',
      ubicacion: 'Huallhua, Vinchos',
      comunidad: 'Huallhua',
      sector: 'Bajo',
      altitud: '3700',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Vinchos',
      latitud: '-13.1250',
      longitud: '-74.3850',
      precision_gps: '5m',
      tipo_suelo: 'Arcilloso',
      textura: 'Fina',
      pendiente: '5-15%',
      fuente_agua: 'RÃ­o',
      sistema_riego: 'A gravedad',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Alta',
      certificacion: 'CONVENCIONAL' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    // Productor 4 - Rosa Ccallpa (Tesorera) - 2 parcelas
    {
      productor_id: productores[3].id,
      codigo: 'PAR-008',
      nombre: 'La Esperanza',
      cultivo: 'Quinua',
      area: 6.00,
      area_certificada: 6.00,
      area_unidad: 'ha',
      ubicacion: 'San Juan de Bolognesi, Acos Vinchos',
      comunidad: 'San Juan de Bolognesi',
      sector: 'Este',
      altitud: '3650',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      latitud: '-13.0900',
      longitud: '-74.4300',
      precision_gps: '3m',
      tipo_suelo: 'Franco limoso',
      textura: 'Media',
      pendiente: '5-15%',
      fuente_agua: 'Manantial',
      sistema_riego: 'A presiÃ³n',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Alta',
      certificacion: 'ORGANICA' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    {
      productor_id: productores[3].id,
      codigo: 'PAR-009',
      nombre: 'Los Ãngeles',
      cultivo: 'Papa Nativa',
      area: 2.80,
      area_certificada: 2.80,
      area_unidad: 'ha',
      ubicacion: 'San Juan de Bolognesi, Acos Vinchos',
      comunidad: 'San Juan de Bolognesi',
      sector: 'Oeste',
      altitud: '3700',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      latitud: '-13.0870',
      longitud: '-74.4350',
      precision_gps: '3m',
      tipo_suelo: 'Franco arcilloso',
      textura: 'Media',
      pendiente: '15-25%',
      fuente_agua: 'RÃ­o',
      sistema_riego: 'A gravedad',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Media',
      certificacion: 'EN_TRANSICION' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    // Productor 5 - Valeriano Quispe (Secretario) - 2 parcelas
    {
      productor_id: productores[4].id,
      codigo: 'PAR-010',
      nombre: 'Chuschi Grande',
      cultivo: 'Quinua',
      area: 7.50,
      area_certificada: 7.50,
      area_unidad: 'ha',
      ubicacion: 'Chuschi, Cangallo',
      comunidad: 'Chuschi',
      sector: 'Central',
      altitud: '3300',
      departamento: 'Ayacucho',
      provincia: 'Cangallo',
      distrito: 'Cangallo',
      latitud: '-13.2200',
      longitud: '-74.3500',
      precision_gps: '3m',
      tipo_suelo: 'Franco limoso',
      textura: 'Media',
      pendiente: '0-5%',
      fuente_agua: 'RÃ­o Chuschi',
      sistema_riego: 'A gravedad',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Alta',
      certificacion: 'ORGANICA' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    {
      productor_id: productores[4].id,
      codigo: 'PAR-011',
      nombre: 'Chuschi Chico',
      cultivo: 'MaÃ­z',
      area: 1.50,
      area_certificada: null,
      area_unidad: 'ha',
      ubicacion: 'Chuschi, Cangallo',
      comunidad: 'Chuschi',
      sector: 'Sur',
      altitud: '3200',
      departamento: 'Ayacucho',
      provincia: 'Cangallo',
      distrito: 'Cangallo',
      latitud: '-13.2250',
      longitud: '-74.3550',
      precision_gps: '5m',
      tipo_suelo: 'Arenoso',
      textura: 'Gruesa',
      pendiente: '5-15%',
      fuente_agua: 'Lluvia',
      sistema_riego: 'SequÃ­a',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Baja',
      certificacion: 'CONVENCIONAL' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    // Productor 6 - Elena Soto (Vocal) - 1 parcela
    {
      productor_id: productores[5].id,
      codigo: 'PAR-012',
      nombre: 'Carmen Alto Verde',
      cultivo: 'Quinua',
      area: 3.00,
      area_certificada: 3.00,
      area_unidad: 'ha',
      ubicacion: 'Carmen Alto, Huamanga',
      comunidad: 'Carmen Alto',
      sector: 'Norte',
      altitud: '3500',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Carmen Alto',
      latitud: '-13.0600',
      longitud: '-74.4800',
      precision_gps: '3m',
      tipo_suelo: 'Franco limoso',
      textura: 'Media',
      pendiente: '5-15%',
      fuente_agua: 'Manantial',
      sistema_riego: 'A presiÃ³n',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Alta',
      certificacion: 'ORGANICA' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    // Productor 7 - Fortunato Lipa - 2 parcelas
    {
      productor_id: productores[6].id,
      codigo: 'PAR-013',
      nombre: 'Pillcuaro Alto',
      cultivo: 'Cebada',
      area: 4.50,
      area_certificada: null,
      area_unidad: 'ha',
      ubicacion: 'Pillcuaro, Acos Vinchos',
      comunidad: 'Pillcuaro',
      sector: 'Alto',
      altitud: '3750',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      latitud: '-13.1100',
      longitud: '-74.4600',
      precision_gps: '5m',
      tipo_suelo: 'Arcilloso',
      textura: 'Fina',
      pendiente: '15-25%',
      fuente_agua: 'Lluvia',
      sistema_riego: 'SequÃ­a',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Baja',
      certificacion: 'CONVENCIONAL' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    {
      productor_id: productores[6].id,
      codigo: 'PAR-014',
      nombre: 'Pillcuaro Bajo',
      cultivo: 'Quinua',
      area: 3.80,
      area_certificada: 3.80,
      area_unidad: 'ha',
      ubicacion: 'Pillcuaro, Acos Vinchos',
      comunidad: 'Pillcuaro',
      sector: 'Bajo',
      altitud: '3550',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      latitud: '-13.1150',
      longitud: '-74.4550',
      precision_gps: '3m',
      tipo_suelo: 'Franco arenoso',
      textura: 'Media',
      pendiente: '5-15%',
      fuente_agua: 'Manantial',
      sistema_riego: 'A gravedad',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Media',
      certificacion: 'EN_TRANSICION' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    // Productor 8 - Cristina Huaman - 1 parcela
    {
      productor_id: productores[7].id,
      codigo: 'PAR-015',
      nombre: 'Tambo Valley',
      cultivo: 'Quinua',
      area: 5.00,
      area_certificada: 5.00,
      area_unidad: 'ha',
      ubicacion: 'Tambo, Los Chankas',
      comunidad: 'Tambo',
      sector: 'Valle',
      altitud: '3200',
      departamento: 'Ayacucho',
      provincia: 'Cangallo',
      distrito: 'Los Chankas',
      latitud: '-13.2000',
      longitud: '-74.3800',
      precision_gps: '3m',
      tipo_suelo: 'Franco limoso',
      textura: 'Media',
      pendiente: '0-5%',
      fuente_agua: 'RÃ­o',
      sistema_riego: 'A gravedad',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Alta',
      certificacion: 'ORGANICA' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    // Productor 11 - Epifanio Ynga - 2 parcelas
    {
      productor_id: productores[10].id,
      codigo: 'PAR-016',
      nombre: 'Pampa Redonda Norte',
      cultivo: 'Quinua',
      area: 6.20,
      area_certificada: 6.20,
      area_unidad: 'ha',
      ubicacion: 'Pampa Cangallo, Acos Vinchos',
      comunidad: 'Pampa Cangallo',
      sector: 'Norte',
      altitud: '3450',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      latitud: '-13.1020',
      longitud: '-74.4180',
      precision_gps: '3m',
      tipo_suelo: 'Franco limoso',
      textura: 'Media',
      pendiente: '5-15%',
      fuente_agua: 'Manantial',
      sistema_riego: 'A presiÃ³n',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Alta',
      certificacion: 'ORGANICA' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    {
      productor_id: productores[10].id,
      codigo: 'PAR-017',
      nombre: 'Pampa Sur',
      cultivo: 'Frijol',
      area: 1.20,
      area_certificada: null,
      area_unidad: 'ha',
      ubicacion: 'Pampa Cangallo, Acos Vinchos',
      comunidad: 'Pampa Cangallo',
      sector: 'Sur',
      altitud: '3380',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      latitud: '-13.1080',
      longitud: '-74.4220',
      precision_gps: '5m',
      tipo_suelo: 'Arcilloso',
      textura: 'Fina',
      pendiente: '15-25%',
      fuente_agua: 'Lluvia',
      sistema_riego: 'SequÃ­a',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Baja',
      certificacion: 'CONVENCIONAL' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    // Productor 12 - Catalina Chavez - 1 parcela
    {
      productor_id: productores[11].id,
      codigo: 'PAR-018',
      nombre: 'San Juan Bajo 2',
      cultivo: 'Tarwi',
      area: 2.20,
      area_certificada: null,
      area_unidad: 'ha',
      ubicacion: 'Chuschi, Cangallo',
      comunidad: 'Chuschi',
      sector: 'Bajo',
      altitud: '3150',
      departamento: 'Ayacucho',
      provincia: 'Cangallo',
      distrito: 'Cangallo',
      latitud: '-13.2280',
      longitud: '-74.3580',
      precision_gps: '5m',
      tipo_suelo: 'Franco arenoso',
      textura: 'Media',
      pendiente: '5-15%',
      fuente_agua: 'RÃ­o',
      sistema_riego: 'A gravedad',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Media',
      certificacion: 'EN_TRANSICION' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
  ];

  const parcelas = [];
  for (const data of parcelasData) {
    const { productor_id, ...rest } = data;
    const p = await prisma.parcela.upsert({
      where: { codigo: data.codigo },
      update: {},
      create: {
        ...rest,
        productores_id: productor_id,
      },
    });
    parcelas.push(p);
  }

  console.log(`âœ… ${parcelas.length} parcelas creadas`);

  // â”€â”€â”€ CAMPAÃ‘AS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  const campaniasData = [
    {
      codigo: 'CAM-2025-001',
      nombre: 'CampaÃ±a Quinua OrgÃ¡nica 2024-2025',
      anio_agricola: '2024-2025',
      fecha_inicio: new Date('2024-10-01'),
      fecha_fin: new Date('2025-06-30'),
      descripcion: 'ProducciÃ³n de quinua orgÃ¡nica certificada de exportaciÃ³n',
      estado: 'ACTIVA' as const,
      responsable: 'Ing. Carlos Mendoza',
      tecnico_coordinador: 'Ing. MarÃ­a GarcÃ­a',
      objetivo: 'Producir quinua orgÃ¡nica certificada garantizando trazabilidad completa',
      permitir_cultivos: true,
      permitir_actividades: true,
      permitir_cosechas: true,
      permitir_inspecciones: true,
      permitir_acopio: true,
      permitir_procesamiento: true,
      visible: true,
      activa: true,
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'CAM-2025-002',
      nombre: 'CampaÃ±a Papa Nativa 2024-2025',
      anio_agricola: '2024-2025',
      fecha_inicio: new Date('2024-11-15'),
      fecha_fin: new Date('2025-05-15'),
      descripcion: 'ProducciÃ³n de papa nativa variedades tradicionales',
      estado: 'ACTIVA' as const,
      responsable: 'Ing. Carlos Mendoza',
      tecnico_coordinador: 'Ing. MarÃ­a GarcÃ­a',
      objetivo: 'Recuperar variedades nativas de papa con manejo agroecolÃ³gico',
      permitir_cultivos: true,
      permitir_actividades: true,
      permitir_cosechas: true,
      permitir_inspecciones: true,
      permitir_acopio: true,
      permitir_procesamiento: true,
      visible: true,
      activa: true,
      activo: true,
      created_by: admin.id,
    },
  ];

  const campanias = [];
  for (const data of campaniasData) {
    const c = await prisma.campanias.upsert({
      where: { codigo: data.codigo },
      update: {},
      create: data,
    });
    campanias.push(c);
  }
  console.log(`âœ… ${campanias.length} campaÃ±as creadas`);

  // â”€â”€â”€ CULTIVOS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  const cultivosData = [
    // CampaÃ±a 1 - Quinua OrgÃ¡nica - Parcelas del productor 1
    {
      campanias_id: campanias[0].id,
      parcela_id: parcelas[0].id,
      codigo: 'CUL-001',
      cultivo: 'Quinua',
      variedad: 'Negra Collana',
      area_sembrada: 5.50,
      fecha_siembra: new Date('2024-11-15'),
      metodo_siembra: 'DIRECTA' as const,
      sistema_productivo: 'ORGANICO' as const,
      tipo_agricultura: 'TRADICIONAL' as const,
      certificacion: 'ORGANICA' as const,
      procedencia_semilla: 'CONSERVADA_POR_AGRICULTOR' as const,
      cantidad_semilla: 25,
      unidad_semilla: 'kg',
      estado: 'EN_DESARROLLO' as const,
      rendimiento_esperado: 1.8,
      produccion_estimada: 9.9,
      destino_produccion: 'VENTA_COOPERATIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    {
      campanias_id: campanias[0].id,
      parcela_id: parcelas[1].id,
      codigo: 'CUL-002',
      cultivo: 'Papa Nativa',
      variedad: 'Huamantanga',
      area_sembrada: 3.20,
      fecha_siembra: new Date('2024-12-01'),
      metodo_siembra: 'TRASPLANTE' as const,
      sistema_productivo: 'ORGANICO' as const,
      tipo_agricultura: 'TRADICIONAL' as const,
      certificacion: 'ORGANICA' as const,
      procedencia_semilla: 'CERTIFICADA' as const,
      cantidad_semilla: 2000,
      unidad_semilla: 'kg',
      estado: 'ACTIVO' as const,
      rendimiento_esperado: 15,
      produccion_estimada: 48,
      destino_produccion: 'VENTA_COOPERATIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    // CampaÃ±a 1 - Parcelas del productor 2
    {
      campanias_id: campanias[0].id,
      parcela_id: parcelas[3].id,
      codigo: 'CUL-003',
      cultivo: 'Quinua',
      variedad: 'Blanca JunÃ­n',
      area_sembrada: 8.00,
      fecha_siembra: new Date('2024-11-20'),
      metodo_siembra: 'DIRECTA' as const,
      sistema_productivo: 'ORGANICO' as const,
      tipo_agricultura: 'TECNIFICADA' as const,
      certificacion: 'ORGANICA' as const,
      procedencia_semilla: 'CERTIFICADA' as const,
      cantidad_semilla: 36,
      unidad_semilla: 'kg',
      estado: 'EN_DESARROLLO' as const,
      rendimiento_esperado: 2.0,
      produccion_estimada: 16,
      destino_produccion: 'VENTA_COOPERATIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    // CampaÃ±a 1 - Parcelas del productor 3
    {
      campanias_id: campanias[0].id,
      parcela_id: parcelas[5].id,
      codigo: 'CUL-004',
      cultivo: 'Quinua',
      variedad: 'Peruanita',
      area_sembrada: 4.00,
      fecha_siembra: new Date('2024-11-10'),
      metodo_siembra: 'DIRECTA' as const,
      sistema_productivo: 'AGROECOLOGICO' as const,
      tipo_agricultura: 'MIXTA' as const,
      certificacion: 'EN_TRANSICION' as const,
      procedencia_semilla: 'COMUN' as const,
      cantidad_semilla: 18,
      unidad_semilla: 'kg',
      estado: 'EN_DESARROLLO' as const,
      rendimiento_esperado: 1.5,
      produccion_estimada: 6,
      destino_produccion: 'AUTOCONSUMO' as const,
      activo: true,
      created_by: admin.id,
    },
    // CampaÃ±a 1 - Parcelas del productor 4
    {
      campanias_id: campanias[0].id,
      parcela_id: parcelas[7].id,
      codigo: 'CUL-005',
      cultivo: 'Quinua',
      variedad: 'Bordaleza',
      area_sembrada: 6.00,
      fecha_siembra: new Date('2024-11-18'),
      metodo_siembra: 'DIRECTA' as const,
      sistema_productivo: 'ORGANICO' as const,
      tipo_agricultura: 'TECNIFICADA' as const,
      certificacion: 'ORGANICA' as const,
      procedencia_semilla: 'CERTIFICADA' as const,
      cantidad_semilla: 27,
      unidad_semilla: 'kg',
      estado: 'ACTIVO' as const,
      rendimiento_esperado: 2.2,
      produccion_estimada: 13.2,
      destino_produccion: 'VENTA_COOPERATIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    // CampaÃ±a 1 - Parcelas del productor 5
    {
      campanias_id: campanias[0].id,
      parcela_id: parcelas[9].id,
      codigo: 'CUL-006',
      cultivo: 'Quinua',
      variedad: 'Negra Collana',
      area_sembrada: 7.50,
      fecha_siembra: new Date('2024-11-12'),
      metodo_siembra: 'DIRECTA' as const,
      sistema_productivo: 'ORGANICO' as const,
      tipo_agricultura: 'TRADICIONAL' as const,
      certificacion: 'ORGANICA' as const,
      procedencia_semilla: 'CONSERVADA_POR_AGRICULTOR' as const,
      cantidad_semilla: 34,
      unidad_semilla: 'kg',
      estado: 'EN_DESARROLLO' as const,
      rendimiento_esperado: 1.8,
      produccion_estimada: 13.5,
      destino_produccion: 'VENTA_COOPERATIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    // CampaÃ±a 2 - Papa Nativa - Parcelas del productor 1
    {
      campanias_id: campanias[1].id,
      parcela_id: parcelas[1].id,
      codigo: 'CUL-007',
      cultivo: 'Papa Nativa',
      variedad: 'Peruanita',
      area_sembrada: 2.00,
      fecha_siembra: new Date('2025-01-10'),
      metodo_siembra: 'TRASPLANTE' as const,
      sistema_productivo: 'AGROECOLOGICO' as const,
      tipo_agricultura: 'TRADICIONAL' as const,
      certificacion: 'SIN_CERTIFICAR' as const,
      procedencia_semilla: 'PRODUCIDA_EN_CAMPO' as const,
      cantidad_semilla: 1200,
      unidad_semilla: 'kg',
      estado: 'ACTIVO' as const,
      rendimiento_esperado: 12,
      produccion_estimada: 24,
      destino_produccion: 'AUTOCONSUMO' as const,
      activo: true,
      created_by: admin.id,
    },
    // CampaÃ±a 2 - Parcelas del productor 3
    {
      campanias_id: campanias[1].id,
      parcela_id: parcelas[6].id,
      codigo: 'CUL-008',
      cultivo: 'Cebada',
      variedad: 'ComÃºn',
      area_sembrada: 1.80,
      fecha_siembra: new Date('2025-01-15'),
      metodo_siembra: 'DIRECTA' as const,
      sistema_productivo: 'CONVENCIONAL' as const,
      tipo_agricultura: 'TRADICIONAL' as const,
      certificacion: 'SIN_CERTIFICAR' as const,
      procedencia_semilla: 'COMUN' as const,
      cantidad_semilla: 40,
      unidad_semilla: 'kg',
      estado: 'ACTIVO' as const,
      rendimiento_esperado: 1.2,
      produccion_estimada: 2.16,
      destino_produccion: 'AUTOCONSUMO' as const,
      activo: true,
      created_by: admin.id,
    },
    // CampaÃ±a 2 - Parcelas del productor 5
    {
      campanias_id: campanias[1].id,
      parcela_id: parcelas[10].id,
      codigo: 'CUL-009',
      cultivo: 'Papa Nativa',
      variedad: 'Andino',
      area_sembrada: 1.50,
      fecha_siembra: new Date('2025-01-05'),
      metodo_siembra: 'TRASPLANTE' as const,
      sistema_productivo: 'AGROECOLOGICO' as const,
      tipo_agricultura: 'MIXTA' as const,
      certificacion: 'SIN_CERTIFICAR' as const,
      procedencia_semilla: 'CONSERVADA_POR_AGRICULTOR' as const,
      cantidad_semilla: 900,
      unidad_semilla: 'kg',
      estado: 'ACTIVO' as const,
      rendimiento_esperado: 10,
      produccion_estimada: 15,
      destino_produccion: 'COMERCIALIZACION_LOCAL' as const,
      activo: true,
      created_by: admin.id,
    },
    // CampaÃ±a 1 - Parcelas del productor 7
    {
      campanias_id: campanias[0].id,
      parcela_id: parcelas[12].id,
      codigo: 'CUL-010',
      cultivo: 'Cebada',
      variedad: 'ComÃºn',
      area_sembrada: 4.50,
      fecha_siembra: new Date('2024-11-25'),
      metodo_siembra: 'DIRECTA' as const,
      sistema_productivo: 'CONVENCIONAL' as const,
      tipo_agricultura: 'TRADICIONAL' as const,
      certificacion: 'SIN_CERTIFICAR' as const,
      procedencia_semilla: 'COMUN' as const,
      cantidad_semilla: 100,
      unidad_semilla: 'kg',
      estado: 'EN_DESARROLLO' as const,
      rendimiento_esperado: 1.0,
      produccion_estimada: 4.5,
      destino_produccion: 'AUTOCONSUMO' as const,
      activo: true,
      created_by: admin.id,
    },
    // CampaÃ±a 1 - Parcelas del productor 8
    {
      campanias_id: campanias[0].id,
      parcela_id: parcelas[14].id,
      codigo: 'CUL-011',
      cultivo: 'Quinua',
      variedad: 'Blanco Gigante',
      area_sembrada: 5.00,
      fecha_siembra: new Date('2024-11-22'),
      metodo_siembra: 'DIRECTA' as const,
      sistema_productivo: 'ORGANICO' as const,
      tipo_agricultura: 'TECNIFICADA' as const,
      certificacion: 'EN_TRANSICION' as const,
      procedencia_semilla: 'CERTIFICADA' as const,
      cantidad_semilla: 22,
      unidad_semilla: 'kg',
      estado: 'EN_DESARROLLO' as const,
      rendimiento_esperado: 2.0,
      produccion_estimada: 10,
      destino_produccion: 'VENTA_COOPERATIVA' as const,
      activo: true,
      created_by: admin.id,
    },
  ];

  const cultivos = [];
  for (const data of cultivosData) {
    const c = await prisma.cultivo.upsert({
      where: { codigo: data.codigo },
      update: {},
      create: data,
    });
    cultivos.push(c);
  }
  console.log(`âœ… ${cultivos.length} cultivos creados`);

  // â”€â”€â”€ ACTIVIDADES â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  const actividadesData = [
    // Actividades para CUL-001 (Quinua Negra Collana)
    {
      cultivo_id: cultivos[0].id,
      codigo: 'ACT-001',
      fecha: new Date('2024-11-10'),
      tipo_actividad: 'PREPARACION_TERRENO' as const,
      descripcion: 'PreparaciÃ³n del terreno para siembra de quinua',
      responsable_tecnico: 'Ing. Carlos Mendoza',
      hora_inicio: '07:00',
      hora_fin: '12:00',
      duracion_estimada: '5 horas',
      prioridad: 'ALTA' as const,
      estado: 'COMPLETADA' as const,
      jornales: 4,
      observaciones_tecnicas: 'Terreno limpio de malezas, laboreo profundo de 20cm',
      objetivo: 'Preparar el suelo para la siembra de quinua orgÃ¡nica',
      resultado: 'Terreno listo para siembra',
      activo: true,
      created_by: admin.id,
    },
    {
      cultivo_id: cultivos[0].id,
      codigo: 'ACT-002',
      fecha: new Date('2024-11-15'),
      tipo_actividad: 'SIEMBRA' as const,
      descripcion: 'Siembra de quinua variedad Negra Collana',
      responsable_tecnico: 'Ing. Carlos Mendoza',
      hora_inicio: '06:00',
      hora_fin: '14:00',
      duracion_estimada: '8 horas',
      prioridad: 'ALTA' as const,
      estado: 'COMPLETADA' as const,
      jornales: 6,
      observaciones_tecnicas: 'Siembra a chaki (surcos), profundidad 2-3cm, distancia 0.30m entre plantas',
      objetivo: 'Establecer cultivo de quinua orgÃ¡nica',
      resultado: 'Siembra completada exitosamente',
      activo: true,
      created_by: admin.id,
    },
    {
      cultivo_id: cultivos[0].id,
      codigo: 'ACT-003',
      fecha: new Date('2024-12-01'),
      tipo_actividad: 'DESHIERBIE' as const,
      descripcion: 'Primer deshierbe manual de quinua',
      responsable_tecnico: 'Ing. Carlos Mendoza',
      hora_inicio: '07:00',
      hora_fin: '13:00',
      duracion_estimada: '6 horas',
      prioridad: 'MEDIA' as const,
      estado: 'COMPLETADA' as const,
      jornales: 5,
      observaciones_tecnicas: 'Deshierbe manual entre lÃ­neas, eliminar malezas competidoras',
      resultado: 'Maleza controlada',
      activo: true,
      created_by: admin.id,
    },
    // Actividades para CUL-002 (Papa Nativa Huamantanga)
    {
      cultivo_id: cultivos[1].id,
      codigo: 'ACT-004',
      fecha: new Date('2024-11-25'),
      tipo_actividad: 'PREPARACION_TERRENO' as const,
      descripcion: 'PreparaciÃ³n de terreno para papa nativa',
      responsable_tecnico: 'Ing. MarÃ­a GarcÃ­a',
      hora_inicio: '06:30',
      hora_fin: '12:30',
      duracion_estimada: '6 horas',
      prioridad: 'ALTA' as const,
      estado: 'COMPLETADA' as const,
      jornales: 3,
      observaciones_tecnicas: 'Laboreo con arado de disco, incorporaciÃ³n de abono orgÃ¡nico',
      resultado: 'Terreno preparado con abono incorporado',
      activo: true,
      created_by: admin.id,
    },
    {
      cultivo_id: cultivos[1].id,
      codigo: 'ACT-005',
      fecha: new Date('2024-12-01'),
      tipo_actividad: 'SIEMBRA' as const,
      descripcion: 'Siembra de papa nativa variedad Huamantanga',
      responsable_tecnico: 'Ing. MarÃ­a GarcÃ­a',
      hora_inicio: '05:00',
      hora_fin: '13:00',
      duracion_estimada: '8 horas',
      prioridad: 'ALTA' as const,
      estado: 'COMPLETADA' as const,
      jornales: 4,
      observaciones_tecnicas: 'Siembra manual en surcos, profundidad 15-20cm',
      resultado: 'Papa sembrada exitosamente',
      activo: true,
      created_by: admin.id,
    },
    // Actividades para CUL-003 (Quinua Blanca JunÃ­n)
    {
      cultivo_id: cultivos[2].id,
      codigo: 'ACT-006',
      fecha: new Date('2024-11-15'),
      tipo_actividad: 'FERTILIZACION' as const,
      descripcion: 'FertilizaciÃ³n de quinua con abono orgÃ¡nico',
      responsable_tecnico: 'Ing. Carlos Mendoza',
      hora_inicio: '07:00',
      hora_fin: '11:00',
      duracion_estimada: '4 horas',
      prioridad: 'MEDIA' as const,
      estado: 'COMPLETADA' as const,
      jornales: 3,
      observaciones_tecnicas: 'AplicaciÃ³n de compost a razÃ³n de 5 ton/ha',
      resultado: 'FertilizaciÃ³n completada',
      activo: true,
      created_by: admin.id,
    },
    // Actividades para CUL-005 (Quinua Bordaleza)
    {
      cultivo_id: cultivos[4].id,
      codigo: 'ACT-007',
      fecha: new Date('2024-11-20'),
      tipo_actividad: 'CONTROL_BIOLOGICO' as const,
      descripcion: 'Control biolÃ³gico de plagas en quinua',
      responsable_tecnico: 'Ing. MarÃ­a GarcÃ­a',
      hora_inicio: '08:00',
      hora_fin: '12:00',
      duracion_estimada: '4 horas',
      prioridad: 'MEDIA' as const,
      estado: 'COMPLETADA' as const,
      jornales: 2,
      observaciones_tecnicas: 'Trampas ferromonales para polilla de la quinua',
      resultado: 'Plaga controlada',
      activo: true,
      created_by: admin.id,
    },
    // Actividades para CUL-006 (Quinua Negra Collana - Chuschi)
    {
      cultivo_id: cultivos[5].id,
      codigo: 'ACT-008',
      fecha: new Date('2024-11-18'),
      tipo_actividad: 'SIEMBRA' as const,
      descripcion: 'Siembra de quinua en zona Chuschi',
      responsable_tecnico: 'Ing. Carlos Mendoza',
      hora_inicio: '06:00',
      hora_fin: '15:00',
      duracion_estimada: '9 horas',
      prioridad: 'ALTA' as const,
      estado: 'COMPLETADA' as const,
      jornales: 7,
      observaciones_tecnicas: 'Siembra en terreno con pendiente, usaræŠ€è¡“ de siembra en contorno',
      resultado: 'Siembra completada en 7.5 hectÃ¡reas',
      activo: true,
      created_by: admin.id,
    },
    // Actividades para CUL-007 (Papa Nativa Peruanita)
    {
      cultivo_id: cultivos[6].id,
      codigo: 'ACT-009',
      fecha: new Date('2025-01-10'),
      tipo_actividad: 'RIEGO' as const,
      descripcion: 'Primer riego de papa nativa',
      responsable_tecnico: 'Ing. MarÃ­a GarcÃ­a',
      hora_inicio: '06:00',
      hora_fin: '10:00',
      duracion_estimada: '4 horas',
      prioridad: 'ALTA' as const,
      estado: 'EN_PROCESO' as const,
      jornales: 2,
      observaciones_tecnicas: 'Riego por gravedad, verificar distribuciÃ³n uniforme',
      objetivo: 'Mantener humedad adecuada para establecimiento',
      activo: true,
      created_by: admin.id,
    },
    // Actividades para CUL-008 (Cebada ComÃºn)
    {
      cultivo_id: cultivos[7].id,
      codigo: 'ACT-010',
      fecha: new Date('2025-01-15'),
      tipo_actividad: 'SIEMBRA' as const,
      descripcion: 'Siembra de cebada variedad ComÃºn',
      responsable_tecnico: 'Ing. Carlos Mendoza',
      hora_inicio: '07:00',
      hora_fin: '11:00',
      duracion_estimada: '4 horas',
      prioridad: 'MEDIA' as const,
      estado: 'PROGRAMADA' as const,
      jornales: 2,
      observaciones_tecnicas: 'Siembra a voleo en terreno preparado',
      objetivo: 'Establecer cultivo de cebada para forraje',
      activo: true,
      created_by: admin.id,
    },
    // Actividades para CUL-011 (Quinua Blanco Gigante)
    {
      cultivo_id: cultivos[10].id,
      codigo: 'ACT-011',
      fecha: new Date('2024-11-25'),
      tipo_actividad: 'APORQUE' as const,
      descripcion: 'Aporque de quinua Blanco Gigante',
      responsable_tecnico: 'Ing. MarÃ­a GarcÃ­a',
      hora_inicio: '07:00',
      hora_fin: '12:00',
      duracion_estimada: '5 horas',
      prioridad: 'MEDIA' as const,
      estado: 'PROGRAMADA' as const,
      jornales: 4,
      observaciones_tecnicas: 'Aporque manual para estabilizar plantas',
      objetivo: 'Fortalecer el sistema radicular de la quinua',
      activo: true,
      created_by: admin.id,
    },
  ];

  const actividades = [];
  for (const data of actividadesData) {
    const a = await prisma.actividades.upsert({
      where: { codigo: data.codigo },
      update: {},
      create: data,
    });
    actividades.push(a);
  }
  console.log(`Ã¢Å“â€¦ ${actividades.length} actividades creadas`);

  // â”€â”€â”€ ACOPIOS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  const acopiosData = [
    // Acopio 1: RecolecciÃ³n de quinua de varios productores
    {
      codigo: 'ACO-2025-01',
      fecha: new Date('2025-03-15'),
      acopiador: 'Juan Mamani',
      vehiculo: 'Toyota Hilux ABC-123',
      ruta_acopio: 'San Juan de Bolognesi - AlmacÃ©n Central',
      estado: 'COMPLETADO' as const,
      observaciones: 'Acopio realizado en maÃ±ana fresca',
      activo: true,
      created_by: admin.id,
      detalles: [
        // Productor 1 - Quinua Negra Collana
        {
          productor_id: productores[0].id,
          cultivo_id: cultivos[0].id,
          observaciones: 'Primera entrega de quinua orgÃ¡nica',
          sacos: [
            { codigo: 'SAC-001', peso: 49.5 },
            { codigo: 'SAC-002', peso: 50.2 },
            { codigo: 'SAC-003', peso: 48.8 },
          ],
        },
        // Productor 2 - Papa Nativa Huamantanga
        {
          productor_id: productores[1].id,
          cultivo_id: cultivos[1].id,
          observaciones: 'Papa de excelente calidad',
          sacos: [
            { codigo: 'SAC-004', peso: 52.3 },
            { codigo: 'SAC-005', peso: 51.8 },
          ],
        },
      ],
    },
    // Acopio 2: RecolecciÃ³n de quinua Blanca JunÃ­n
    {
      codigo: 'ACO-2025-02',
      fecha: new Date('2025-03-20'),
      acopiador: 'Carlos Quispe',
      vehiculo: 'Nissan NP300 DEF-456',
      ruta_acopio: 'Pampa Cangallo Grande - Planta Procesadora',
      estado: 'EN_PLANTA' as const,
      observaciones: 'Acopio para exportaciÃ³n',
      activo: true,
      created_by: admin.id,
      detalles: [
        {
          productor_id: productores[2].id,
          cultivo_id: cultivos[2].id,
          observaciones: 'Quinua blanca de alta calidad',
          sacos: [
            { codigo: 'SAC-006', peso: 50.1 },
            { codigo: 'SAC-007', peso: 49.7 },
            { codigo: 'SAC-008', peso: 50.3 },
            { codigo: 'SAC-009', peso: 48.9 },
            { codigo: 'SAC-010', peso: 51.0 },
          ],
        },
      ],
    },
    // Acopio 3: RecolecciÃ³n mixta
    {
      codigo: 'ACO-2025-03',
      fecha: new Date('2025-04-01'),
      acopiador: 'Pedro Huanca',
      vehiculo: 'Isuzu NHR GHI-789',
      ruta_acopio: 'Chuschi - Mercado Mayorista',
      estado: 'COMPLETADO' as const,
      observaciones: 'Acopio con condiciones climÃ¡ticas adversas',
      activo: true,
      created_by: admin.id,
      detalles: [
        // Productor 5 - Quinua Bordaleza
        {
          productor_id: productores[4].id,
          cultivo_id: cultivos[4].id,
          observaciones: 'Calidad regular, algunas impurezas',
          sacos: [
            { codigo: 'SAC-011', peso: 48.5 },
            { codigo: 'SAC-012', peso: 47.8 },
            { codigo: 'SAC-013', peso: 49.2 },
          ],
        },
        // Productor 8 - Cebada
        {
          productor_id: productores[7].id,
          cultivo_id: cultivos[7].id,
          observaciones: 'Primera entrega de cebada',
          sacos: [
            { codigo: 'SAC-014', peso: 45.0 },
            { codigo: 'SAC-015', peso: 44.5 },
          ],
        },
      ],
    },
  ];

  const acopios = [];
  for (const data of acopiosData) {
    const { detalles: detallesData, ...acopioData } = data;
    const totalSacos = detallesData.reduce((sum, d) => sum + d.sacos.length, 0);
    const pesoTotal = detallesData.reduce((sum, d) => sum + d.sacos.reduce((s, saco) => s + saco.peso, 0), 0);

    const a = await prisma.acopio.upsert({
      where: { codigo: acopioData.codigo },
      update: {},
      create: {
        ...acopioData,
        total_sacos: totalSacos,
        peso_total: pesoTotal,
        detalles: {
          create: detallesData.map(d => ({
            productor_id: d.productor_id,
            cultivo_id: d.cultivo_id,
            observaciones: d.observaciones,
            total_sacos: d.sacos.length,
            peso_total: d.sacos.reduce((sum, s) => sum + s.peso, 0),
            sacos: {
              create: d.sacos,
            },
          })),
        },
      },
    });
    acopios.push(a);
  }
  console.log(`âœ… ${acopios.length} acopios creados`);

  // ─── RECEPCIONES ─────────────────────────────────────────
  const recepcionesData = [
    // Recepción del primer acopio
    {
      acopio_id: acopios[0].id,
      lote_productor: 'LP-001',
      fecha: new Date('2025-03-16'),
      responsable: 'Ing. Carlos Mendoza',
      planta: 'Planta Procesadora Central',
      sacos: 5,
      peso_campo: 252.6,
      peso_bruto: 250.0,
      tara: 2.5,
      peso_neto: 247.5,
      diferencia: -5.1,
      humedad: 12.8,
      impurezas: 1.5,
      estado: 'EN_CONTROL_CALIDAD' as const,
      observaciones: 'Primera recepción de la campaña',
      activo: true,
      created_by: admin.id,
    },
    // Recepción del segundo acopio
    {
      acopio_id: acopios[1].id,
      lote_productor: 'LP-002',
      fecha: new Date('2025-03-21'),
      responsable: 'Ing. María García',
      planta: 'Planta Procesadora Central',
      sacos: 5,
      peso_campo: 250.0,
      peso_bruto: 248.5,
      tara: 2.0,
      peso_neto: 246.5,
      diferencia: -3.5,
      humedad: 11.5,
      impurezas: 0.8,
      estado: 'DISPONIBLE' as const,
      observaciones: 'Producto de excelente calidad',
      activo: true,
      created_by: admin.id,
    },
    // Recepción manual (sin acopio - otra empresa)
    {
      acopio_id: null,
      lote_productor: 'LP-EXT-001',
      fecha: new Date('2025-04-05'),
      responsable: 'Ing. Carlos Mendoza',
      planta: 'Planta Procesadora Central',
      sacos: 10,
      peso_campo: 500.0,
      peso_bruto: 498.0,
      tara: 5.0,
      peso_neto: 493.0,
      diferencia: -7.0,
      humedad: 13.2,
      impurezas: 2.1,
      estado: 'PENDIENTE_PESAJE' as const,
      observaciones: 'Recepción de proveedor externo - Cooperativa San José',
      activo: true,
      created_by: admin.id,
    },
  ];

  const recepciones = [];
  for (const data of recepcionesData) {
    const r = await prisma.recepcion.create({
      data: {
        ...data,
        codigo: `RCP-2025-${String(recepciones.length + 1).padStart(2, '0')}`,
      },
    });

    // Crear sacos individuales para cada recepción
    const sacosCount = data.sacos;
    const sacosDetalle = [];
    for (let i = 1; i <= sacosCount; i++) {
      const pesoBase = data.peso_campo / sacosCount;
      const peso = Number((pesoBase + (Math.random() * 4 - 2)).toFixed(2));
      sacosDetalle.push({
        recepcion_id: r.id,
        codigo: `SAC-RCP-${String(recepciones.length + 1).padStart(2, '0')}-${String(i).padStart(3, '0')}`,
        peso,
      });
    }
    await prisma.recepcion_saco.createMany({ data: sacosDetalle });

    recepciones.push(r);
  }
  console.log(`âœ… ${recepciones.length} recepciones creadas`);
  console.log(`   ðŸ‘¤ Usuarios:       3`);
  console.log(`   ðŸ‘¨â€ðŸŒ¾ Productores:   ${productores.length}`);
  console.log(`   ðŸ‘¨â€ðŸ‘©â€ðŸ‘§ Familiares:   ${cleanedFamiliares.length}`);
  console.log(`   ðŸŒ¾ Parcelas:      ${parcelas.length}`);
  console.log(`   ðŸŽ¯ CampaÃ±as:      ${campanias.length}`);

  const org = parcelas.filter(p => p.certificacion === 'ORGANICA').length;
  const trans = parcelas.filter(p => p.certificacion === 'EN_TRANSICION').length;
  const conv = parcelas.filter(p => p.certificacion === 'CONVENCIONAL').length;
  console.log(`\n   ðŸŒ¿ CertificaciÃ³n:`);
  console.log(`      OrgÃ¡nica:       ${org} parcelas`);
  console.log(`      En transiciÃ³n:  ${trans} parcelas`);
  console.log(`      Convencional:   ${conv} parcelas`);

  const totalArea = parcelas.reduce((sum, p) => sum + Number(p.area), 0);
  const areaCert = parcelas.filter(p => p.certificacion === 'ORGANICA').reduce((sum, p) => sum + Number(p.area), 0);
  console.log(`\n   ðŸ“ Superficie total: ${totalArea} ha`);
  console.log(`   âœ… Ãrea certificada: ${areaCert} ha (${((areaCert / totalArea) * 100).toFixed(1)}%)`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
    console.log('\nðŸŽ‰ Seed completado exitosamente.');
  })
  .catch(async (e) => {
    console.error('âŒ Error en seed:', e);
    await prisma.$disconnect();
    process.exit(1);
  });
