import { PrismaClient } from '@prisma/client';
import * as bcrypt from 'bcrypt';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Sembrando datos de prueba...');

  const passwordHash = await bcrypt.hash('Admin123!', 10);
  const passwordHashDemo = await bcrypt.hash('Demo123!', 10);

  // ─── USUARIOS ───────────────────────────────────────────────
  const admin = await prisma.usuarios.upsert({
    where: { email: 'admin@agrodata.com' },
    update: {},
    create: {
      nombre: 'Administrador',
      email: 'admin@agrodata.com',
      password: passwordHash,
      rol: 'ADMIN',
      activo: true,
    },
  });

  const usuario1 = await prisma.usuarios.upsert({
    where: { email: 'carlos.mendoza@agrodata.com' },
    update: {},
    create: {
      nombre: 'Carlos Mendoza',
      email: 'carlos.mendoza@agrodata.com',
      password: passwordHashDemo,
      rol: 'USER',
      activo: true,
    },
  });

  const usuario2 = await prisma.usuarios.upsert({
    where: { email: 'maria.garcia@agrodata.com' },
    update: {},
    create: {
      nombre: 'María García',
      email: 'maria.garcia@agrodata.com',
      password: passwordHashDemo,
      rol: 'USER',
      activo: true,
    },
  });

  console.log('✅ Usuarios creados');

  // ─── PRODUCTORES ────────────────────────────────────────────
  const productoresData = [
    {
      codigo: 'SOC-001',
      dni: '45123678',
      nombres: 'Teófilo',
      apellido_paterno: 'Huanca',
      apellido_materno: 'Quispe',
      sexo: 'MASCULINO' as const,
      fecha_nacimiento: new Date('1975-03-15'),
      estado_civil: 'CASADO' as const,
      telefono: '951234567',
      correo: 'teofilo.huanca@gmail.com',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      comunidad: 'San Juan de Bolognesi',
      direccion: 'Jr. Los Andes 456',
      nivel_educativo: 'SECUNDARIA' as const,
      idioma_principal: 'QUECHUA' as const,
      idioma_secundario: 'ESPANOL' as const,
      estado: 'ACTIVO' as const,
      activo: true,
      fecha_ingreso: new Date('2020-01-15'),
      organizacion: 'Cooperativa Agraria San Juan',
      cargo: 'PRESIDENTE' as const,
      created_by: admin.id,
    },
    {
      codigo: 'SOC-002',
      dni: '46234567',
      nombres: 'Juana',
      apellido_paterno: 'Mamani',
      apellido_materno: 'Condori',
      sexo: 'FEMENINO' as const,
      fecha_nacimiento: new Date('1980-07-22'),
      estado_civil: 'CASADO' as const,
      telefono: '952345678',
      correo: 'juana.mamani@hotmail.com',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      comunidad: 'Pampa Cangallo',
      direccion: 'Calle Primavera 123',
      nivel_educativo: 'PRIMARIA' as const,
      idioma_principal: 'QUECHUA' as const,
      idioma_secundario: 'ESPANOL' as const,
      estado: 'ACTIVO' as const,
      activo: true,
      fecha_ingreso: new Date('2020-02-10'),
      organizacion: 'Cooperativa Agraria San Juan',
      cargo: 'VICEPRESIDENTE' as const,
      created_by: admin.id,
    },
    {
      codigo: 'SOC-003',
      dni: '47345678',
      nombres: 'Miguel',
      apellido_paterno: 'Ticona',
      apellido_materno: 'Yupanqui',
      sexo: 'MASCULINO' as const,
      fecha_nacimiento: new Date('1968-11-05'),
      estado_civil: 'CASADO' as const,
      telefono: '953456789',
      correo: null,
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Vinchos',
      comunidad: 'Huallhua',
      direccion: 'Sin dirección',
      nivel_educativo: 'SIN_ESTUDIOS' as const,
      idioma_principal: 'QUECHUA' as const,
      idioma_secundario: 'NINGUNO' as const,
      estado: 'ACTIVO' as const,
      activo: true,
      fecha_ingreso: new Date('2020-01-15'),
      organizacion: 'Cooperativa Agraria San Juan',
      cargo: 'SOCIO' as const,
      created_by: admin.id,
    },
    {
      codigo: 'SOC-004',
      dni: '48456789',
      nombres: 'Rosa',
      apellido_paterno: 'Ccallpa',
      apellido_materno: 'Mendoza',
      sexo: 'FEMENINO' as const,
      fecha_nacimiento: new Date('1985-04-18'),
      estado_civil: 'CONVIVIENTE' as const,
      telefono: '954567890',
      correo: 'rosa.ccallpa@gmail.com',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      comunidad: 'San Juan de Bolognesi',
      direccion: 'Av. Progreso 789',
      nivel_educativo: 'TECNICO' as const,
      idioma_principal: 'ESPANOL' as const,
      idioma_secundario: 'QUECHUA' as const,
      estado: 'ACTIVO' as const,
      activo: true,
      fecha_ingreso: new Date('2021-03-20'),
      organizacion: 'Cooperativa Agraria San Juan',
      cargo: 'TESORERO' as const,
      created_by: admin.id,
    },
    {
      codigo: 'SOC-005',
      dni: '49567890',
      nombres: 'Valeriano',
      apellido_paterno: 'Quispe',
      apellido_materno: 'Huanca',
      sexo: 'MASCULINO' as const,
      fecha_nacimiento: new Date('1972-09-30'),
      estado_civil: 'VIUDO' as const,
      telefono: '955678901',
      correo: null,
      departamento: 'Ayacucho',
      provincia: 'Cangallo',
      distrito: 'Cangallo',
      comunidad: 'Chuschi',
      direccion: 'Campamento s/n',
      nivel_educativo: 'PRIMARIA' as const,
      idioma_principal: 'QUECHUA' as const,
      idioma_secundario: 'ESPANOL' as const,
      estado: 'ACTIVO' as const,
      activo: true,
      fecha_ingreso: new Date('2020-05-01'),
      organizacion: 'Cooperativa Agraria San Juan',
      cargo: 'SECRETARIO' as const,
      created_by: admin.id,
    },
    {
      codigo: 'SOC-006',
      dni: '41678901',
      nouns: 'Elena',
      apellido_paterno: 'Soto',
      apellido_materno: 'Ramos',
      sexo: 'FEMENINO' as const,
      fecha_nacimiento: new Date('1990-01-12'),
      estado_civil: 'SOLTERO' as const,
      telefono: '956789012',
      correo: 'elena.soto@outlook.com',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Carmen Alto',
      comunidad: 'Carmen Alto',
      direccion: 'Jr. San Martín 321',
      nivel_educativo: 'UNIVERSITARIO' as const,
      idioma_principal: 'ESPANOL' as const,
      idioma_secundario: 'QUECHUA' as const,
      estado: 'ACTIVO' as const,
      activo: true,
      fecha_ingreso: new Date('2022-06-15'),
      organizacion: 'Cooperativa Agraria San Juan',
      cargo: 'VOCAL' as const,
      created_by: admin.id,
    },
    {
      codigo: 'SOC-007',
      dni: '42789012',
      nombres: 'Fortunato',
      apellido_paterno: 'Lipa',
      apellido_materno: 'Ccorahua',
      sexo: 'MASCULINO' as const,
      fecha_nacimiento: new Date('1965-06-25'),
      estado_civil: 'CASADO' as const,
      telefono: '957890123',
      correo: null,
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      comunidad: 'Pillcuaro',
      direccion: 'Sin dirección',
      nivel_educativo: 'PRIMARIA' as const,
      idioma_principal: 'QUECHUA' as const,
      idioma_secundario: 'NINGUNO' as const,
      estado: 'ACTIVO' as const,
      activo: true,
      fecha_ingreso: new Date('2020-01-15'),
      organizacion: 'Cooperativa Agraria San Juan',
      cargo: 'SOCIO' as const,
      created_by: admin.id,
    },
    {
      codigo: 'SOC-008',
      dni: '43890123',
      nombres: 'Cristina',
      apellido_paterno: 'Huaman',
      apellido_materno: 'Poma',
      sexo: 'FEMENINO' as const,
      fecha_nacimiento: new Date('1978-12-08'),
      estado_civil: 'CASADO' as const,
      telefono: '958901234',
      correo: 'cristina.huaman@gmail.com',
      departamento: 'Ayacucho',
      provincia: 'Cangallo',
      distrito: 'Los Chankas',
      comunidad: 'Tambo',
      direccion: 'Av. Libertad 567',
      nivel_educativo: 'SECUNDARIA' as const,
      idioma_principal: 'ESPANOL' as const,
      idioma_secundario: 'QUECHUA' as const,
      estado: 'ACTIVO' as const,
      activo: true,
      fecha_ingreso: new Date('2021-07-01'),
      organizacion: 'Cooperativa Agraria San Juan',
      cargo: 'SOCIO' as const,
      created_by: admin.id,
    },
    {
      codigo: 'SOC-009',
      dni: '44901234',
      nombres: 'Bernardo',
      apellido_paterno: 'Ccahuana',
      apellido_materno: 'Zea',
      sexo: 'MASCULINO' as const,
      fecha_nacimiento: new Date('1982-02-14'),
      estado_civil: 'CASADO' as const,
      telefono: '959012345',
      correo: null,
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Vinchos',
      comunidad: 'San Lorenzo de Quinti',
      direccion: 'Calle Los Olivos 890',
      nivel_educativo: 'SECUNDARIA' as const,
      idioma_principal: 'QUECHUA' as const,
      idioma_secundario: 'ESPANOL' as const,
      estado: 'INACTIVO' as const,
      activo: false,
      fecha_ingreso: new Date('2020-08-10'),
      organizacion: 'Cooperativa Agraria San Juan',
      cargo: 'SOCIO' as const,
      created_by: admin.id,
    },
    {
      codigo: 'SOC-010',
      dni: '45012345',
      nombres: 'Luisa',
      apellido_paterno: 'Palomino',
      apellido_materno: 'Garcia',
      sexo: 'FEMENINO' as const,
      fecha_nacimiento: new Date('1995-08-20'),
      estado_civil: 'SOLTERO' as const,
      telefono: '960123456',
      correo: 'luisa.palomino@yahoo.com',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      comunidad: 'San Juan de Bolognesi',
      direccion: 'Jr. Comercio 234',
      nivel_educativo: 'UNIVERSITARIO' as const,
      idioma_principal: 'ESPANOL' as const,
      idioma_secundario: 'NINGUNO' as const,
      estado: 'SUSPENDIDO' as const,
      activo: true,
      fecha_ingreso: new Date('2023-01-10'),
      organizacion: 'Cooperativa Agraria San Juan',
      cargo: 'SOCIO' as const,
      created_by: admin.id,
    },
    {
      codigo: 'SOC-011',
      dni: '46123456',
      nombres: 'Epifanio',
      apellido_paterno: 'Ynga',
      apellido_materno: 'Ttito',
      sexo: 'MASCULINO' as const,
      fecha_nacimiento: new Date('1970-05-03'),
      estado_civil: 'CASADO' as const,
      telefono: '961234567',
      correo: null,
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      comunidad: 'Pampa Cangallo',
      direccion: 'Sin dirección',
      nivel_educativo: 'PRIMARIA' as const,
      idioma_principal: 'QUECHUA' as const,
      idioma_secundario: 'ESPANOL' as const,
      estado: 'ACTIVO' as const,
      activo: true,
      fecha_ingreso: new Date('2020-03-05'),
      organizacion: 'Cooperativa Agraria San Juan',
      cargo: 'SOCIO' as const,
      created_by: admin.id,
    },
    {
      codigo: 'SOC-012',
      dni: '47234567',
      nouns: 'Catalina',
      apellido_paterno: 'Chavez',
      apellido_materno: 'Alarcon',
      sexo: 'FEMENINO' as const,
      fecha_nacimiento: new Date('1988-10-17'),
      estado_civil: 'CASADO' as const,
      telefono: '962345678',
      correo: 'catalina.chavez@gmail.com',
      departamento: 'Ayacucho',
      provincia: 'Cangallo',
      distrito: 'Cangallo',
      comunidad: 'Chuschi',
      direccion: 'Calle San Juan 654',
      nivel_educativo: 'TECNICO' as const,
      idioma_principal: 'ESPANOL' as const,
      idioma_secundario: 'QUECHUA' as const,
      estado: 'ACTIVO' as const,
      activo: true,
      fecha_ingreso: new Date('2022-04-12'),
      organizacion: 'Cooperativa Agraria San Juan',
      cargo: 'SOCIO' as const,
      created_by: admin.id,
    },
  ];

  // Fix fields that had typos
  const cleanedData = productoresData.map((p) => {
    const clean = { ...p };
    if ('nouns' in clean) {
      (clean as any).nombres = (clean as any).nouns;
      delete (clean as any).nouns;
    }
    return clean;
  });

  const productores = [];
  for (const data of cleanedData) {
    const p = await prisma.productores.upsert({
      where: { dni: data.dni },
      update: {},
      create: data as any,
    });
    productores.push(p);
  }

  console.log(`✅ ${productores.length} productores creados`);

  // ─── FAMILIARES ─────────────────────────────────────────────
  const familiaresData = [
    { productor_id: productores[0].id, nombres: 'Mercedes Quispe de Huanca', parentesco: 'Esposa', dni: '45123679', sexo: 'FEMENINO' as const, fecha_nacimiento: new Date('1978-05-20'), ocupacion: 'Agricultora', dependiente: false, vive_con_productor: true },
    { productor_id: productores[0].id, nombres: 'Jhonatan Huanca Quispe', parentesco: 'Hijo', sexo: 'MASCULINO' as const, fecha_nacimiento: new Date('2000-08-10'), ocupacion: 'Estudiante', nivel_educativo: 'SECUNDARIA' as const, dependiente: true, vive_con_productor: true },
    { productor_id: productores[0].id, nombres: 'Katherin Huanca Quispe', parentesco: 'Hija', sexo: 'FEMENINO' as const, fecha_nacimiento: new Date('2004-03-25'), ocupacion: 'Estudiante', nivel_educativo: 'SECUNDARIA' as const, dependiente: true, vive_con_productor: true },
    { productor_id: productores[1].id, nombres: 'Alejandro Mamani Condori', parentesco: 'Esposo', dni: '46234568', sexo: 'MASCULINO' as const, fecha_nacimiento: new Date('1978-09-12'), ocupacion: 'Agricultor', dependiente: false, vive_con_productor: true },
    { productor_id: productores[1].id, nombres: 'Soledad Mamani Mamani', parentesco: 'Hija', sexo: 'FEMENINO' as const, fecha_nacimiento: new Date('2002-12-01'), ocupacion: 'Agricultora', dependiente: true, vive_con_productor: true },
    { productor_id: productores[2].id, nouns: 'Rufina Yupanqui de Ticona', parentesco: 'Esposa', dni: '47345679', sexo: 'FEMENINO' as const, fecha_nacimiento: new Date('1970-07-15'), ocupacion: 'Agricultora', dependiente: false, vive_con_productor: true },
    { productor_id: productores[2].id, nombres: 'Brian Ticona Yupanqui', parentesco: 'Hijo', sexo: 'MASCULINO' as const, fecha_nacimiento: new Date('1998-02-28'), ocupacion: 'Agricultor', dependiente: false, vive_con_productor: false },
    { productor_id: productores[4].id, nouns: 'Gladys Yupanqui de Quispe', parentesco: 'Esposa', sexo: 'FEMENINO' as const, fecha_nacimiento: new Date('1975-11-10'), ocupacion: 'Agricultora', dependiente: false, vive_con_productor: true },
    { productor_id: productores[4].id, nombres: 'Yerson Quispe Yupanqui', parentesco: 'Hijo', sexo: 'MASCULINO' as const, fecha_nacimiento: new Date('2001-06-18'), ocupacion: 'Estudiante', nivel_educativo: 'TECNICO' as const, dependiente: true, vive_con_productor: true },
    { productor_id: productores[6].id, nouns: 'Gregoria Ccorahua de Lipa', parentesco: 'Esposa', sexo: 'FEMENINO' as const, fecha_nacimiento: new Date('1968-04-22'), ocupacion: 'Agricultora', dependiente: false, vive_con_productor: true },
    { productor_id: productores[7].id, nouns: 'Mario Huaman Poma', parentesco: 'Esposo', dni: '43890124', sexo: 'MASCULINO' as const, fecha_nacimiento: new Date('1976-03-30'), ocupacion: 'Agricultor', dependiente: false, vive_con_productor: true },
    { productor_id: productores[10].id, nouns: 'Gladys Ttito de Ynga', parentesco: 'Esposa', sexo: 'FEMENINO' as const, fecha_nacimiento: new Date('1973-08-05'), ocupacion: 'Agricultora', dependiente: false, vive_con_productor: true },
  ];

  const cleanedFamiliares = familiaresData.map((f) => {
    const clean = { ...f };
    if ('nouns' in clean) {
      (clean as any).nombres = (clean as any).nouns;
      delete (clean as any).nouns;
    }
    return clean;
  });

  for (const f of cleanedFamiliares) {
    await prisma.familiares_productor.create({ data: f as any });
  }

  console.log(`✅ ${cleanedFamiliares.length} familiares creados`);

  // ─── PARCELAS ───────────────────────────────────────────────
  const parcelasData = [
    // Productor 1 - Teófilo Huanca (Presidente) - 3 parcelas
    {
      productor_id: productores[0].id,
      codigo: 'PAR-001',
      nombre: 'San Juan Alto',
      cultivo: 'Quinua',
      area: 5.50,
      area_certificada: 5.50,
      area_unidad: 'ha',
      ubicacion: 'San Juan de Bolognesi, Acos Vinchos',
      comunidad: 'San Juan de Bolognesi',
      sector: 'Alto',
      altitud: '3800',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      latitud: '-13.0850',
      longitud: '-74.4520',
      precision_gps: '5m',
      tipo_suelo: 'Franco arcilloso',
      textura: 'Media',
      pendiente: '15-25%',
      fuente_agua: 'Manantial',
      sistema_riego: 'Sequía',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Media',
      certificacion: 'ORGANICA' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    {
      productor_id: productores[0].id,
      codigo: 'PAR-002',
      nombre: 'San Juan Bajo',
      cultivo: 'Papa Nativa',
      area: 3.20,
      area_certificada: 3.20,
      area_unidad: 'ha',
      ubicacion: 'San Juan de Bolognesi, Acos Vinchos',
      comunidad: 'San Juan de Bolognesi',
      sector: 'Bajo',
      altitud: '3600',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      latitud: '-13.0920',
      longitud: '-74.4480',
      precision_gps: '3m',
      tipo_suelo: 'Franco arenoso',
      textura: 'Media',
      pendiente: '5-15%',
      fuente_agua: 'Río',
      sistema_riego: 'A gravedad',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Alta',
      certificacion: 'ORGANICA' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    {
      productor_id: productores[0].id,
      codigo: 'PAR-003',
      nombre: 'Pampa Redonda',
      cultivo: 'Cebada',
      area: 2.00,
      area_certificada: null,
      area_unidad: 'ha',
      ubicacion: 'San Juan de Bolognesi, Acos Vinchos',
      comunidad: 'San Juan de Bolognesi',
      sector: 'Pampa',
      altitud: '3500',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      latitud: '-13.0980',
      longitud: '-74.4390',
      precision_gps: '5m',
      tipo_suelo: 'Arcilloso',
      textura: 'Fina',
      pendiente: '0-5%',
      fuente_agua: 'Lluvia',
      sistema_riego: 'Sequía',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Baja',
      certificacion: 'EN_TRANSICION' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    // Productor 2 - Juana Mamani (Vicepresidenta) - 2 parcelas
    {
      productor_id: productores[1].id,
      codigo: 'PAR-004',
      nombre: 'Pampa Cangallo Grande',
      cultivo: 'Quinua',
      area: 8.00,
      area_certificada: 8.00,
      area_unidad: 'ha',
      ubicacion: 'Pampa Cangallo, Acos Vinchos',
      comunidad: 'Pampa Cangallo',
      sector: 'Central',
      altitud: '3400',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      latitud: '-13.1050',
      longitud: '-74.4200',
      precision_gps: '3m',
      tipo_suelo: 'Franco limoso',
      textura: 'Media',
      pendiente: '5-15%',
      fuente_agua: 'Río',
      sistema_riego: 'A gravedad',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Alta',
      certificacion: 'ORGANICA' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    {
      productor_id: productores[1].id,
      codigo: 'PAR-005',
      nombre: 'Pampa Chica',
      cultivo: 'Tarwi',
      area: 2.50,
      area_certificada: null,
      area_unidad: 'ha',
      ubicacion: 'Pampa Cangallo, Acos Vinchos',
      comunidad: 'Pampa Cangallo',
      sector: 'Norte',
      altitud: '3350',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      latitud: '-13.1000',
      longitud: '-74.4150',
      precision_gps: '5m',
      tipo_suelo: 'Franco arcilloso',
      textura: 'Media',
      pendiente: '15-25%',
      fuente_agua: 'Lluvia',
      sistema_riego: 'Sequía',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Baja',
      certificacion: 'CONVENCIONAL' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    // Productor 3 - Miguel Ticona - 2 parcelas
    {
      productor_id: productores[2].id,
      codigo: 'PAR-006',
      nombre: 'Huallhua Superior',
      cultivo: 'Quinua',
      area: 4.00,
      area_certificada: 4.00,
      area_unidad: 'ha',
      ubicacion: 'Huallhua, Vinchos',
      comunidad: 'Huallhua',
      sector: 'Alto',
      altitud: '3900',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Vinchos',
      latitud: '-13.1200',
      longitud: '-74.3800',
      precision_gps: '5m',
      tipo_suelo: 'Franco arenoso',
      textura: 'Media',
      pendiente: '15-25%',
      fuente_agua: 'Manantial',
      sistema_riego: 'Sequía',
      zona_agroecologica: 'Suní',
      disponibilidad_agua: 'Media',
      certificacion: 'ORGANICA' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    {
      productor_id: productores[2].id,
      codigo: 'PAR-007',
      nombre: 'Huallhua Inferior',
      cultivo: 'Frijol',
      area: 1.80,
      area_certificada: null,
      area_unidad: 'ha',
      ubicacion: 'Huallhua, Vinchos',
      comunidad: 'Huallhua',
      sector: 'Bajo',
      altitud: '3700',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Vinchos',
      latitud: '-13.1250',
      longitud: '-74.3850',
      precision_gps: '5m',
      tipo_suelo: 'Arcilloso',
      textura: 'Fina',
      pendiente: '5-15%',
      fuente_agua: 'Río',
      sistema_riego: 'A gravedad',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Alta',
      certificacion: 'CONVENCIONAL' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    // Productor 4 - Rosa Ccallpa (Tesorera) - 2 parcelas
    {
      productor_id: productores[3].id,
      codigo: 'PAR-008',
      nombre: 'La Esperanza',
      cultivo: 'Quinua',
      area: 6.00,
      area_certificada: 6.00,
      area_unidad: 'ha',
      ubicacion: 'San Juan de Bolognesi, Acos Vinchos',
      comunidad: 'San Juan de Bolognesi',
      sector: 'Este',
      altitud: '3650',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      latitud: '-13.0900',
      longitud: '-74.4300',
      precision_gps: '3m',
      tipo_suelo: 'Franco limoso',
      textura: 'Media',
      pendiente: '5-15%',
      fuente_agua: 'Manantial',
      sistema_riego: 'A presión',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Alta',
      certificacion: 'ORGANICA' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    {
      productor_id: productores[3].id,
      codigo: 'PAR-009',
      nombre: 'Los Ángeles',
      cultivo: 'Papa Nativa',
      area: 2.80,
      area_certificada: 2.80,
      area_unidad: 'ha',
      ubicacion: 'San Juan de Bolognesi, Acos Vinchos',
      comunidad: 'San Juan de Bolognesi',
      sector: 'Oeste',
      altitud: '3700',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      latitud: '-13.0870',
      longitud: '-74.4350',
      precision_gps: '3m',
      tipo_suelo: 'Franco arcilloso',
      textura: 'Media',
      pendiente: '15-25%',
      fuente_agua: 'Río',
      sistema_riego: 'A gravedad',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Media',
      certificacion: 'EN_TRANSICION' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    // Productor 5 - Valeriano Quispe (Secretario) - 2 parcelas
    {
      productor_id: productores[4].id,
      codigo: 'PAR-010',
      nombre: 'Chuschi Grande',
      cultivo: 'Quinua',
      area: 7.50,
      area_certificada: 7.50,
      area_unidad: 'ha',
      ubicacion: 'Chuschi, Cangallo',
      comunidad: 'Chuschi',
      sector: 'Central',
      altitud: '3300',
      departamento: 'Ayacucho',
      provincia: 'Cangallo',
      distrito: 'Cangallo',
      latitud: '-13.2200',
      longitud: '-74.3500',
      precision_gps: '3m',
      tipo_suelo: 'Franco limoso',
      textura: 'Media',
      pendiente: '0-5%',
      fuente_agua: 'Río Chuschi',
      sistema_riego: 'A gravedad',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Alta',
      certificacion: 'ORGANICA' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    {
      productor_id: productores[4].id,
      codigo: 'PAR-011',
      nombre: 'Chuschi Chico',
      cultivo: 'Maíz',
      area: 1.50,
      area_certificada: null,
      area_unidad: 'ha',
      ubicacion: 'Chuschi, Cangallo',
      comunidad: 'Chuschi',
      sector: 'Sur',
      altitud: '3200',
      departamento: 'Ayacucho',
      provincia: 'Cangallo',
      distrito: 'Cangallo',
      latitud: '-13.2250',
      longitud: '-74.3550',
      precision_gps: '5m',
      tipo_suelo: 'Arenoso',
      textura: 'Gruesa',
      pendiente: '5-15%',
      fuente_agua: 'Lluvia',
      sistema_riego: 'Sequía',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Baja',
      certificacion: 'CONVENCIONAL' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    // Productor 6 - Elena Soto (Vocal) - 1 parcela
    {
      productor_id: productores[5].id,
      codigo: 'PAR-012',
      nombre: 'Carmen Alto Verde',
      cultivo: 'Quinua',
      area: 3.00,
      area_certificada: 3.00,
      area_unidad: 'ha',
      ubicacion: 'Carmen Alto, Huamanga',
      comunidad: 'Carmen Alto',
      sector: 'Norte',
      altitud: '3500',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Carmen Alto',
      latitud: '-13.0600',
      longitud: '-74.4800',
      precision_gps: '3m',
      tipo_suelo: 'Franco limoso',
      textura: 'Media',
      pendiente: '5-15%',
      fuente_agua: 'Manantial',
      sistema_riego: 'A presión',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Alta',
      certificacion: 'ORGANICA' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    // Productor 7 - Fortunato Lipa - 2 parcelas
    {
      productor_id: productores[6].id,
      codigo: 'PAR-013',
      nombre: 'Pillcuaro Alto',
      cultivo: 'Cebada',
      area: 4.50,
      area_certificada: null,
      area_unidad: 'ha',
      ubicacion: 'Pillcuaro, Acos Vinchos',
      comunidad: 'Pillcuaro',
      sector: 'Alto',
      altitud: '3750',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      latitud: '-13.1100',
      longitud: '-74.4600',
      precision_gps: '5m',
      tipo_suelo: 'Arcilloso',
      textura: 'Fina',
      pendiente: '15-25%',
      fuente_agua: 'Lluvia',
      sistema_riego: 'Sequía',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Baja',
      certificacion: 'CONVENCIONAL' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    {
      productor_id: productores[6].id,
      codigo: 'PAR-014',
      nombre: 'Pillcuaro Bajo',
      cultivo: 'Quinua',
      area: 3.80,
      area_certificada: 3.80,
      area_unidad: 'ha',
      ubicacion: 'Pillcuaro, Acos Vinchos',
      comunidad: 'Pillcuaro',
      sector: 'Bajo',
      altitud: '3550',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      latitud: '-13.1150',
      longitud: '-74.4550',
      precision_gps: '3m',
      tipo_suelo: 'Franco arenoso',
      textura: 'Media',
      pendiente: '5-15%',
      fuente_agua: 'Manantial',
      sistema_riego: 'A gravedad',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Media',
      certificacion: 'EN_TRANSICION' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    // Productor 8 - Cristina Huaman - 1 parcela
    {
      productor_id: productores[7].id,
      codigo: 'PAR-015',
      nombre: 'Tambo Valley',
      cultivo: 'Quinua',
      area: 5.00,
      area_certificada: 5.00,
      area_unidad: 'ha',
      ubicacion: 'Tambo, Los Chankas',
      comunidad: 'Tambo',
      sector: 'Valle',
      altitud: '3200',
      departamento: 'Ayacucho',
      provincia: 'Cangallo',
      distrito: 'Los Chankas',
      latitud: '-13.2000',
      longitud: '-74.3800',
      precision_gps: '3m',
      tipo_suelo: 'Franco limoso',
      textura: 'Media',
      pendiente: '0-5%',
      fuente_agua: 'Río',
      sistema_riego: 'A gravedad',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Alta',
      certificacion: 'ORGANICA' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    // Productor 11 - Epifanio Ynga - 2 parcelas
    {
      productor_id: productores[10].id,
      codigo: 'PAR-016',
      nombre: 'Pampa Redonda Norte',
      cultivo: 'Quinua',
      area: 6.20,
      area_certificada: 6.20,
      area_unidad: 'ha',
      ubicacion: 'Pampa Cangallo, Acos Vinchos',
      comunidad: 'Pampa Cangallo',
      sector: 'Norte',
      altitud: '3450',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      latitud: '-13.1020',
      longitud: '-74.4180',
      precision_gps: '3m',
      tipo_suelo: 'Franco limoso',
      textura: 'Media',
      pendiente: '5-15%',
      fuente_agua: 'Manantial',
      sistema_riego: 'A presión',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Alta',
      certificacion: 'ORGANICA' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    {
      productor_id: productores[10].id,
      codigo: 'PAR-017',
      nombre: 'Pampa Sur',
      cultivo: 'Frijol',
      area: 1.20,
      area_certificada: null,
      area_unidad: 'ha',
      ubicacion: 'Pampa Cangallo, Acos Vinchos',
      comunidad: 'Pampa Cangallo',
      sector: 'Sur',
      altitud: '3380',
      departamento: 'Ayacucho',
      provincia: 'Huamanga',
      distrito: 'Acos Vinchos',
      latitud: '-13.1080',
      longitud: '-74.4220',
      precision_gps: '5m',
      tipo_suelo: 'Arcilloso',
      textura: 'Fina',
      pendiente: '15-25%',
      fuente_agua: 'Lluvia',
      sistema_riego: 'Sequía',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Baja',
      certificacion: 'CONVENCIONAL' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
    // Productor 12 - Catalina Chavez - 1 parcela
    {
      productor_id: productores[11].id,
      codigo: 'PAR-018',
      nombre: 'San Juan Bajo 2',
      cultivo: 'Tarwi',
      area: 2.20,
      area_certificada: null,
      area_unidad: 'ha',
      ubicacion: 'Chuschi, Cangallo',
      comunidad: 'Chuschi',
      sector: 'Bajo',
      altitud: '3150',
      departamento: 'Ayacucho',
      provincia: 'Cangallo',
      distrito: 'Cangallo',
      latitud: '-13.2280',
      longitud: '-74.3580',
      precision_gps: '5m',
      tipo_suelo: 'Franco arenoso',
      textura: 'Media',
      pendiente: '5-15%',
      fuente_agua: 'Río',
      sistema_riego: 'A gravedad',
      zona_agroecologica: 'Quechua',
      disponibilidad_agua: 'Media',
      certificacion: 'EN_TRANSICION' as const,
      estado: 'ACTIVA' as const,
      activo: true,
      created_by: admin.id,
    },
  ];

  const parcelas = [];
  for (const data of parcelasData) {
    const p = await prisma.parcelas_productor.upsert({
      where: { codigo: data.codigo },
      update: {},
      create: data,
    });
    parcelas.push(p);
  }

  console.log(`✅ ${parcelas.length} parcelas creadas`);

  // ─── CAMPAÑAS ──────────────────────────────────────────────
  const campaniasData = [
    {
      codigo: 'CMP-2025-001',
      nombre: 'Campaña Quinua Orgánica 2024-2025',
      anio_agricola: '2024-2025',
      fecha_inicio: new Date('2024-10-01'),
      fecha_fin: new Date('2025-06-30'),
      descripcion: 'Producción de quinua orgánica certificada de exportación',
      estado: 'ACTIVA' as const,
      responsable: 'Ing. Carlos Mendoza',
      tecnico_coordinador: 'Ing. María García',
      objetivo: 'Producir quinua orgánica certificada garantizando trazabilidad completa',
      permitir_cultivos: true,
      permitir_actividades: true,
      permitir_cosechas: true,
      permitir_inspecciones: true,
      permitir_acopio: true,
      permitir_procesamiento: true,
      visible: true,
      activa: true,
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'CMP-2025-002',
      nombre: 'Campaña Papa Nativa 2024-2025',
      anio_agricola: '2024-2025',
      fecha_inicio: new Date('2024-11-15'),
      fecha_fin: new Date('2025-05-15'),
      descripcion: 'Producción de papa nativa variedades tradicionales',
      estado: 'ACTIVA' as const,
      responsable: 'Ing. Carlos Mendoza',
      tecnico_coordinador: 'Ing. María García',
      objetivo: 'Recuperar variedades nativas de papa con manejo agroecológico',
      permitir_cultivos: true,
      permitir_actividades: true,
      permitir_cosechas: true,
      permitir_inspecciones: true,
      permitir_acopio: true,
      permitir_procesamiento: true,
      visible: true,
      activa: true,
      activo: true,
      created_by: admin.id,
    },
  ];

  const campanias = [];
  for (const data of campaniasData) {
    const c = await prisma.campanias.upsert({
      where: { codigo: data.codigo },
      update: {},
      create: data,
    });
    campanias.push(c);
  }
  console.log(`✅ ${campanias.length} campañas creadas`);

  // ─── LOTES ─────────────────────────────────────────────────
  const lotesData = [
    {
      codigo: 'LOTE-2025-001',
      nombre: 'Quinua Orgánica San Juan',
      campania_id: campanias[0].id,
      cultivo: 'Quinua',
      origen: 'San Juan de Bolognesi',
      peso_inicial: 4500,
      peso_disponible: 3200,
      unidad: 'kg',
      estado: 'DISPONIBLE' as const,
      fecha_produccion: new Date('2025-03-15'),
      calidad: 'Primera',
      certificacion: 'Orgánica',
      ubicacion: 'Almacén Central',
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'LOTE-2025-002',
      nombre: 'Quinua Orgánica Pampa Cangallo',
      campania_id: campanias[0].id,
      cultivo: 'Quinua',
      origen: 'Pampa Cangallo',
      peso_inicial: 6200,
      peso_disponible: 6200,
      unidad: 'kg',
      estado: 'REGISTRADO' as const,
      fecha_produccion: new Date('2025-04-01'),
      calidad: 'Primera',
      certificacion: 'Orgánica',
      ubicacion: 'Almacén Central',
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'LOTE-2025-003',
      nombre: 'Papa Nativa Chuschi',
      campania_id: campanias[1].id,
      cultivo: 'Papa Nativa',
      origen: 'Chuschi',
      peso_inicial: 2800,
      peso_disponible: 1500,
      unidad: 'kg',
      estado: 'EN_PROCESAMIENTO' as const,
      fecha_produccion: new Date('2025-02-20'),
      calidad: 'Segunda',
      certificacion: 'En Transición',
      ubicacion: 'Planta Procesadora',
      activo: true,
      created_by: admin.id,
    },
  ];

  const lotes = [];
  for (const data of lotesData) {
    const l = await prisma.lotes.upsert({
      where: { codigo: data.codigo },
      update: {},
      create: data,
    });
    lotes.push(l);
  }
  console.log(`✅ ${lotes.length} lotes creados`);

  // ─── INVENTARIO ────────────────────────────────────────────
  const inventarioData = [
    {
      codigo: 'INV-001',
      producto: 'Guano de corral',
      categoria: 'Fertilizante',
      unidad: 'kg',
      cantidad_actual: 2500,
      cantidad_minima: 500,
      cantidad_maxima: 5000,
      ubicacion: 'Almacén de Insumos',
      estado: 'DISPONIBLE' as const,
      fecha_ingreso: new Date('2025-01-10'),
      proveedor: 'Cooperativa Local',
      costo_unitario: 0.80,
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'INV-002',
      producto: 'Compost orgánico',
      categoria: 'Fertilizante',
      unidad: 'kg',
      cantidad_actual: 1800,
      cantidad_minima: 300,
      cantidad_maxima: 4000,
      ubicacion: 'Almacén de Insumos',
      estado: 'DISPONIBLE' as const,
      fecha_ingreso: new Date('2025-02-05'),
      proveedor: 'Producción propia',
      costo_unitario: 0.50,
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'INV-003',
      producto: 'Aceite de neem',
      categoria: 'Biocontrolador',
      unidad: 'litros',
      cantidad_actual: 50,
      cantidad_minima: 20,
      cantidad_maxima: 200,
      ubicacion: 'Almacén de Insumos',
      estado: 'DISPONIBLE' as const,
      fecha_ingreso: new Date('2025-03-01'),
      fecha_vencimiento: new Date('2026-03-01'),
      proveedor: 'Biocontroladores SA',
      costo_unitario: 15.00,
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'INV-004',
      producto: 'Semilla de Quinua Real',
      categoria: 'Semilla',
      unidad: 'kg',
      cantidad_actual: 120,
      cantidad_minima: 50,
      cantidad_maxima: 500,
      ubicacion: 'Bodega de Semillas',
      estado: 'DISPONIBLE' as const,
      fecha_ingreso: new Date('2025-01-20'),
      fecha_vencimiento: new Date('2025-12-31'),
      proveedor: 'INIA',
      costo_unitario: 8.50,
      activo: true,
      created_by: admin.id,
    },
  ];

  const inventarioItems = [];
  for (const data of inventarioData) {
    const i = await prisma.inventario.upsert({
      where: { codigo: data.codigo },
      update: {},
      create: data,
    });
    inventarioItems.push(i);
  }
  console.log(`✅ ${inventarioItems.length} items de inventario creados`);

  // ─── TRAZABILIDAD ──────────────────────────────────────────
  const trazabilidadData = [
    {
      codigo: 'TRZ-2025-001',
      lote_id: lotes[0].id,
      producto: 'Quinua Real Orgánica',
      cultivo: 'Quinua',
      origen: 'San Juan de Bolognesi, Acos Vinchos',
      productor: 'Teófilo Huanca Quispe',
      parcela: 'PAR-001 · San Juan Alto',
      comunidad: 'San Juan de Bolognesi',
      fecha_siembra: new Date('2024-11-10'),
      fecha_cosecha: new Date('2025-03-10'),
      fecha_procesamiento: new Date('2025-04-05'),
      peso_total: 4500,
      unidad: 'kg',
      calidad: 'Primera',
      certificacion: 'Orgánica',
      destino: 'Exportación',
      estado: 'COMPLETADO',
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'TRZ-2025-002',
      producto: 'Quinua Orgánica Premium',
      cultivo: 'Quinua',
      origen: 'Pampa Cangallo, Acos Vinchos',
      productor: 'Juana Mamani Condori',
      parcela: 'PAR-004 · Pampa Cangallo Grande',
      comunidad: 'Pampa Cangallo',
      fecha_siembra: new Date('2024-11-15'),
      fecha_cosecha: new Date('2025-03-20'),
      peso_total: 6200,
      unidad: 'kg',
      calidad: 'Primera',
      certificacion: 'Orgánica',
      destino: 'Mercado Nacional',
      estado: 'EN_PROCESO',
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'TRZ-2025-003',
      producto: 'Papa Nativa Mixta',
      cultivo: 'Papa Nativa',
      origen: 'Chuschi, Cangallo',
      productor: 'Valeriano Quispe Huanca',
      parcela: 'PAR-010 · Chuschi Grande',
      comunidad: 'Chuschi',
      fecha_siembra: new Date('2024-12-01'),
      fecha_cosecha: new Date('2025-04-15'),
      peso_total: 2800,
      unidad: 'kg',
      calidad: 'Segunda',
      certificacion: 'En Transición',
      destino: 'Mercado Local',
      estado: 'REGISTRADO',
      activo: true,
      created_by: admin.id,
    },
  ];

  const trazabilidades = [];
  for (const data of trazabilidadData) {
    const t = await prisma.trazabilidad.upsert({
      where: { codigo: data.codigo },
      update: {},
      create: data,
    });
    trazabilidades.push(t);
  }
  console.log(`✅ ${trazabilidades.length} registros de trazabilidad creados`);

  // ─── CULTIVOS ──────────────────────────────────────────────
  const cultivosData = [
    {
      codigo: 'CUL-001',
      campania_id: campanias[0].id,
      productor_id: productores[0].id,
      parcela_id: parcelas[0].id,
      cultivo: 'Quinua',
      variedad: 'Real',
      area_sembrada: 5.50,
      fecha_siembra: new Date('2024-11-10'),
      metodo_siembra: 'DIRECTA' as const,
      sistema_productivo: 'ORGANICO' as const,
      certificacion: 'ORGANICA' as const,
      estado: 'EN_DESARROLLO' as const,
      rendimiento_esperado: 1.8,
      produccion_estimada: 9.9,
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'CUL-002',
      campania_id: campanias[0].id,
      productor_id: productores[1].id,
      parcela_id: parcelas[3].id,
      cultivo: 'Quinua',
      variedad: 'Negra',
      area_sembrada: 8.00,
      fecha_siembra: new Date('2024-11-15'),
      metodo_siembra: 'DIRECTA' as const,
      sistema_productivo: 'ORGANICO' as const,
      certificacion: 'ORGANICA' as const,
      estado: 'EN_DESARROLLO' as const,
      rendimiento_esperado: 1.6,
      produccion_estimada: 12.8,
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'CUL-003',
      campania_id: campanias[0].id,
      productor_id: productores[2].id,
      parcela_id: parcelas[5].id,
      cultivo: 'Quinua',
      variedad: 'Blanca',
      area_sembrada: 4.00,
      fecha_siembra: new Date('2024-11-12'),
      metodo_siembra: 'DIRECTA' as const,
      sistema_productivo: 'ORGANICO' as const,
      certificacion: 'ORGANICA' as const,
      estado: 'EN_DESARROLLO' as const,
      rendimiento_esperado: 1.5,
      produccion_estimada: 6.0,
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'CUL-004',
      campania_id: campanias[0].id,
      productor_id: productores[3].id,
      parcela_id: parcelas[7].id,
      cultivo: 'Quinua',
      variedad: 'Real',
      area_sembrada: 6.00,
      fecha_siembra: new Date('2024-11-18'),
      metodo_siembra: 'DIRECTA' as const,
      sistema_productivo: 'ORGANICO' as const,
      certificacion: 'ORGANICA' as const,
      estado: 'ACTIVO' as const,
      rendimiento_esperado: 1.7,
      produccion_estimada: 10.2,
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'CUL-005',
      campania_id: campanias[0].id,
      productor_id: productores[4].id,
      parcela_id: parcelas[9].id,
      cultivo: 'Quinua',
      variedad: 'Híbrida',
      area_sembrada: 7.50,
      fecha_siembra: new Date('2024-11-20'),
      metodo_siembra: 'DIRECTA' as const,
      sistema_productivo: 'EN_TRANSICION' as const,
      certificacion: 'EN_TRANSICION' as const,
      estado: 'EN_DESARROLLO' as const,
      rendimiento_esperado: 1.4,
      produccion_estimada: 10.5,
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'CUL-006',
      campania_id: campanias[0].id,
      productor_id: productores[5].id,
      parcela_id: parcelas[11].id,
      cultivo: 'Quinua',
      variedad: 'Real',
      area_sembrada: 3.00,
      fecha_siembra: new Date('2024-11-22'),
      metodo_siembra: 'DIRECTA' as const,
      sistema_productivo: 'ORGANICO' as const,
      certificacion: 'ORGANICA' as const,
      estado: 'ACTIVO' as const,
      rendimiento_esperado: 1.8,
      produccion_estimada: 5.4,
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'CUL-007',
      campania_id: campanias[0].id,
      productor_id: productores[10].id,
      parcela_id: parcelas[15].id,
      cultivo: 'Quinua',
      variedad: 'Real',
      area_sembrada: 6.20,
      fecha_siembra: new Date('2024-11-25'),
      metodo_siembra: 'DIRECTA' as const,
      sistema_productivo: 'ORGANICO' as const,
      certificacion: 'ORGANICA' as const,
      estado: 'EN_DESARROLLO' as const,
      rendimiento_esperado: 1.7,
      produccion_estimada: 10.54,
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'CUL-008',
      campania_id: campanias[0].id,
      productor_id: productores[7].id,
      parcela_id: parcelas[14].id,
      cultivo: 'Quinua',
      variedad: 'Blanca',
      area_sembrada: 5.00,
      fecha_siembra: new Date('2024-11-28'),
      metodo_siembra: 'DIRECTA' as const,
      sistema_productivo: 'ORGANICO' as const,
      certificacion: 'ORGANICA' as const,
      estado: 'ACTIVO' as const,
      rendimiento_esperado: 1.6,
      produccion_estimada: 8.0,
      activo: true,
      created_by: admin.id,
    },
  ];

  const cultivos = [];
  for (const data of cultivosData) {
    const c = await prisma.cultivos.create({ data });
    cultivos.push(c);
  }
  console.log(`✅ ${cultivos.length} cultivos creados`);

  // ─── ACTIVIDADES ──────────────────────────────────────────
  const actividadesData = [
    {
      codigo: 'ACT-001',
      campania_id: campanias[0].id,
      productor_id: productores[0].id,
      parcela_id: parcelas[0].id,
      cultivo_id: cultivos[0].id,
      fecha: new Date('2024-11-05'),
      tipo_actividad: 'FERTILIZACION' as const,
      descripcion: 'Aplicación de guano de corral pre-siembra',
      responsable_tecnico: 'Ing. Carlos Mendoza',
      prioridad: 'ALTA' as const,
      estado: 'COMPLETADA' as const,
      jornales: 4,
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'ACT-002',
      campania_id: campanias[0].id,
      productor_id: productores[0].id,
      parcela_id: parcelas[0].id,
      cultivo_id: cultivos[0].id,
      fecha: new Date('2024-11-10'),
      tipo_actividad: 'SIEMBRA' as const,
      descripcion: 'Siembra directa de quinua Real en surcos',
      responsable_tecnico: 'Ing. María García',
      prioridad: 'ALTA' as const,
      estado: 'COMPLETADA' as const,
      jornales: 6,
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'ACT-003',
      campania_id: campanias[0].id,
      productor_id: productores[1].id,
      parcela_id: parcelas[3].id,
      cultivo_id: cultivos[1].id,
      fecha: new Date('2024-11-15'),
      tipo_actividad: 'SIEMBRA' as const,
      descripcion: 'Siembra de quinua Negra variedad local',
      responsable_tecnico: 'Ing. María García',
      prioridad: 'ALTA' as const,
      estado: 'COMPLETADA' as const,
      jornales: 8,
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'ACT-004',
      campania_id: campanias[0].id,
      productor_id: productores[2].id,
      parcela_id: parcelas[5].id,
      cultivo_id: cultivos[2].id,
      fecha: new Date('2024-12-01'),
      tipo_actividad: 'COMPOSTAJE' as const,
      descripcion: 'Aplicación de compostaje orgánico a parcela',
      responsable_tecnico: 'Ing. Carlos Mendoza',
      prioridad: 'MEDIA' as const,
      estado: 'COMPLETADA' as const,
      jornales: 3,
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'ACT-005',
      campania_id: campanias[0].id,
      productor_id: productores[3].id,
      parcela_id: parcelas[7].id,
      cultivo_id: cultivos[3].id,
      fecha: new Date('2024-12-10'),
      tipo_actividad: 'CONTROL_BIOLOGICO' as const,
      descripcion: 'Liberación de Trichograma para control de gusano blanco',
      responsable_tecnico: 'Ing. María García',
      prioridad: 'ALTA' as const,
      estado: 'COMPLETADA' as const,
      jornales: 2,
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'ACT-006',
      campania_id: campanias[0].id,
      productor_id: productores[4].id,
      parcela_id: parcelas[9].id,
      cultivo_id: cultivos[4].id,
      fecha: new Date('2025-01-15'),
      tipo_actividad: 'DESHIERBIE' as const,
      descripcion: 'Control manual de malezas en etapa vegetativa',
      responsable_tecnico: 'Ing. Carlos Mendoza',
      prioridad: 'MEDIA' as const,
      estado: 'EN_PROCESO' as const,
      jornales: 10,
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'ACT-007',
      campania_id: campanias[0].id,
      productor_id: productores[10].id,
      parcela_id: parcelas[15].id,
      cultivo_id: cultivos[6].id,
      fecha: new Date('2025-02-01'),
      tipo_actividad: 'MANEJO_PLAGAS' as const,
      descripcion: 'Monitoreo y control de polilla de la quinua',
      responsable_tecnico: 'Ing. María García',
      prioridad: 'ALTA' as const,
      estado: 'PROGRAMADA' as const,
      jornales: 5,
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'ACT-008',
      campania_id: campanias[0].id,
      productor_id: productores[7].id,
      parcela_id: parcelas[14].id,
      cultivo_id: cultivos[7].id,
      fecha: new Date('2025-02-15'),
      tipo_actividad: 'RIEGO' as const,
      descripcion: 'Riego por gravedad en período crítico',
      responsable_tecnico: 'Ing. Carlos Mendoza',
      prioridad: 'MEDIA' as const,
      estado: 'PROGRAMADA' as const,
      jornales: 3,
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'ACT-009',
      campania_id: campanias[0].id,
      productor_id: productores[0].id,
      parcela_id: parcelas[0].id,
      cultivo_id: cultivos[0].id,
      fecha: new Date('2025-03-10'),
      tipo_actividad: 'COSECHA' as const,
      descripcion: 'Cosecha mecánica y trilla de quinua Real',
      responsable_tecnico: 'Ing. Carlos Mendoza',
      prioridad: 'ALTA' as const,
      estado: 'PROGRAMADA' as const,
      jornales: 12,
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'ACT-010',
      campania_id: campanias[1].id,
      productor_id: productores[4].id,
      parcela_id: parcelas[10].id,
      fecha: new Date('2024-12-01'),
      tipo_actividad: 'PREPARACION_TERRENO' as const,
      descripcion: 'Arado y rastreo de terreno para papa nativa',
      responsable_tecnico: 'Ing. María García',
      prioridad: 'ALTA' as const,
      estado: 'COMPLETADA' as const,
      jornales: 6,
      activo: true,
      created_by: admin.id,
    },
  ];

  const actividades = [];
  for (const data of actividadesData) {
    const a = await prisma.actividades.create({ data });
    actividades.push(a);
  }
  console.log(`✅ ${actividades.length} actividades creadas`);

  // ─── INSPECCIONES ──────────────────────────────────────────
  const inspeccionesData = [
    {
      codigo: 'INSP-001',
      campania_id: campanias[0].id,
      productor_id: productores[0].id,
      parcela_id: parcelas[0].id,
      cultivo_id: cultivos[0].id,
      fecha: new Date('2024-12-15'),
      inspector: 'Ing. María García',
      estado: 'APROBADA' as const,
      resultado: 'CONFORME' as const,
      observaciones: 'Parcela en buenas condiciones. Cultivo con buen desarrollo vegetativo.',
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'INSP-002',
      campania_id: campanias[0].id,
      productor_id: productores[1].id,
      parcela_id: parcelas[3].id,
      cultivo_id: cultivos[1].id,
      fecha: new Date('2024-12-20'),
      inspector: 'Ing. Carlos Mendoza',
      estado: 'APROBADA' as const,
      resultado: 'CONFORME_CON_OBSERVACIONES' as const,
      observaciones: 'Se recomienda reforzar control de malezas en sectores orientales.',
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'INSP-003',
      campania_id: campanias[0].id,
      productor_id: productores[4].id,
      parcela_id: parcelas[9].id,
      cultivo_id: cultivos[4].id,
      fecha: new Date('2025-01-10'),
      inspector: 'Ing. María García',
      estado: 'NO_CONFORME' as const,
      resultado: 'NO_CONFORME' as const,
      observaciones: 'Se detecta presencia de gusano blanco. Se requiere acción inmediata de control biológico.',
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'INSP-004',
      campania_id: campanias[0].id,
      productor_id: productores[10].id,
      parcela_id: parcelas[15].id,
      cultivo_id: cultivos[6].id,
      fecha: new Date('2025-02-20'),
      inspector: 'Ing. Carlos Mendoza',
      estado: 'PENDIENTE' as const,
      resultado: null,
      observaciones: null,
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'INSP-005',
      campania_id: campanias[1].id,
      productor_id: productores[4].id,
      parcela_id: parcelas[10].id,
      fecha: new Date('2025-01-25'),
      inspector: 'Ing. María García',
      estado: 'PENDIENTE' as const,
      resultado: null,
      observaciones: null,
      activo: true,
      created_by: admin.id,
    },
  ];

  const inspecciones = [];
  for (const data of inspeccionesData) {
    const i = await prisma.inspecciones.create({ data });
    inspecciones.push(i);
  }
  console.log(`✅ ${inspecciones.length} inspecciones creadas`);

  // ─── ACOPIOS ───────────────────────────────────────────────
  const acopiosData = [
    {
      codigo: 'ACP-001',
      campania_id: campanias[0].id,
      productor_id: productores[0].id,
      parcela_id: parcelas[0].id,
      cultivo_id: cultivos[0].id,
      fecha: new Date('2025-03-15'),
      acopiador: 'Juan Pérez',
      vehiculo: 'Toyota Hilux ABC-123',
      lote_productor: 'LP-TEO-001',
      total_sacos: 45,
      peso_total: 2250,
      estado: 'COMPLETADO' as const,
      estado_producto: 'EXCELENTE' as const,
      humedad: 12.5,
      impurezas: 1.2,
      observaciones: 'Quinua de excelente calidad, limpia y uniforme.',
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'ACP-002',
      campania_id: campanias[0].id,
      productor_id: productores[1].id,
      parcela_id: parcelas[3].id,
      cultivo_id: cultivos[1].id,
      fecha: new Date('2025-03-20'),
      acopiador: 'Carlos Ramos',
      vehiculo: 'Nissan NP300 DEF-456',
      lote_productor: 'LP-JUA-001',
      total_sacos: 62,
      peso_total: 3100,
      estado: 'COMPLETADO' as const,
      estado_producto: 'BUENO' as const,
      humedad: 13.0,
      impurezas: 1.8,
      observaciones: 'Buena calidad, quelques semillas con humedad ligeramente elevada.',
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'ACP-003',
      campania_id: campanias[0].id,
      productor_id: productores[3].id,
      parcela_id: parcelas[7].id,
      cultivo_id: cultivos[3].id,
      fecha: new Date('2025-03-25'),
      acopiador: 'Juan Pérez',
      vehiculo: 'Toyota Hilux ABC-123',
      lote_productor: 'LP-ROS-001',
      total_sacos: 50,
      peso_total: 2500,
      estado: 'EN_PLANTA' as const,
      estado_producto: 'EXCELENTE' as const,
      humedad: 11.8,
      impurezas: 0.9,
      observaciones: 'Producto de primera calidad, apto para exportación.',
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'ACP-004',
      campania_id: campanias[0].id,
      productor_id: productores[10].id,
      parcela_id: parcelas[15].id,
      cultivo_id: cultivos[6].id,
      fecha: new Date('2025-04-01'),
      acopiador: 'Carlos Ramos',
      vehiculo: 'Nissan NP300 DEF-456',
      lote_productor: 'LP-EPI-001',
      total_sacos: 55,
      peso_total: 2750,
      estado: 'EN_PROCESO' as const,
      estado_producto: 'BUENO' as const,
      humedad: 13.5,
      impurezas: 2.1,
      observaciones: 'En proceso de verificación de calidad.',
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'ACP-005',
      campania_id: campanias[0].id,
      productor_id: productores[7].id,
      parcela_id: parcelas[14].id,
      cultivo_id: cultivos[7].id,
      fecha: new Date('2025-04-05'),
      acopiador: 'Juan Pérez',
      vehiculo: 'Toyota Hilux ABC-123',
      lote_productor: 'LP-CRI-001',
      total_sacos: 40,
      peso_total: 2000,
      estado: 'EN_PROCESO' as const,
      estado_producto: 'REGULAR' as const,
      humedad: 14.2,
      impurezas: 3.0,
      observaciones: 'Humedad un poco alta, requiere secado antes de procesamiento.',
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'ACP-006',
      campania_id: campanias[1].id,
      productor_id: productores[4].id,
      parcela_id: parcelas[10].id,
      fecha: new Date('2025-04-10'),
      acopiador: 'Carlos Ramos',
      vehiculo: 'Nissan NP300 DEF-456',
      lote_productor: 'LP-VAL-001',
      total_sacos: 30,
      peso_total: 1500,
      estado: 'EN_PROCESO' as const,
      estado_producto: 'BUENO' as const,
      humedad: 11.5,
      impurezas: 1.5,
      observaciones: 'Papa nativa de buena calidad.',
      activo: true,
      created_by: admin.id,
    },
  ];

  const acopios = [];
  for (const data of acopiosData) {
    const a = await prisma.acopios.create({ data });
    acopios.push(a);
  }
  console.log(`✅ ${acopios.length} acopios creados`);

  // ─── RECEPCIONES ──────────────────────────────────────────
  const recepcionesData = [
    {
      codigo: 'RCP-001',
      campania_id: campanias[0].id,
      acopio_id: acopios[0].id,
      lote_productor: 'LP-TEO-001',
      fecha: new Date('2025-03-16'),
      responsable: 'Ing. Carlos Mendoza',
      planta: 'Planta Procesadora San Juan',
      sacos: 45,
      peso_campo: 2250,
      peso_bruto: 2250,
      tara: 225,
      peso_neto: 2025,
      humedad: 12.5,
      estado_producto: 'EXCELENTE' as const,
      categoria: 'PRIMERA' as const,
      destino: 'PROCESAMIENTO' as const,
      resultado: 'ACEPTADO' as const,
      estado: 'DISPONIBLE' as const,
      observaciones: 'Recepción sin observaciones. Producto de exportación.',
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'RCP-002',
      campania_id: campanias[0].id,
      acopio_id: acopios[1].id,
      lote_productor: 'LP-JUA-001',
      fecha: new Date('2025-03-21'),
      responsable: 'Ing. María García',
      planta: 'Planta Procesadora San Juan',
      sacos: 62,
      peso_campo: 3100,
      peso_bruto: 3100,
      tara: 310,
      peso_neto: 2790,
      humedad: 13.0,
      estado_producto: 'BUENO' as const,
      categoria: 'SEGUNDA' as const,
      destino: 'PROCESAMIENTO' as const,
      resultado: 'ACEPTADO_CON_OBSERVACIONES' as const,
      estado: 'DISPONIBLE' as const,
      observaciones: 'Humedad ligeramente elevada. Se recomienda secado previo.',
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'RCP-003',
      campania_id: campanias[0].id,
      acopio_id: acopios[2].id,
      lote_productor: 'LP-ROS-001',
      fecha: new Date('2025-03-26'),
      responsable: 'Ing. Carlos Mendoza',
      planta: 'Planta Procesadora San Juan',
      sacos: 50,
      peso_campo: 2500,
      peso_bruto: 2500,
      tara: 250,
      peso_neto: 2250,
      humedad: 11.8,
      estado_producto: 'EXCELENTE' as const,
      categoria: 'PRIMERA' as const,
      destino: 'ALMACEN_TEMPORAL' as const,
      resultado: 'ACEPTADO' as const,
      estado: 'PENDIENTE_PESAJE' as const,
      observaciones: 'Producto excelente. En espera de espacio en almacén.',
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'RCP-004',
      campania_id: campanias[1].id,
      acopio_id: acopios[5].id,
      lote_productor: 'LP-VAL-001',
      fecha: new Date('2025-04-11'),
      responsable: 'Ing. María García',
      planta: 'Planta Procesadora Chuschi',
      sacos: 30,
      peso_campo: 1500,
      peso_bruto: 1500,
      tara: 150,
      peso_neto: 1350,
      humedad: 11.5,
      estado_producto: 'BUENO' as const,
      categoria: 'SEGUNDA' as const,
      destino: 'PROCESAMIENTO' as const,
      resultado: 'ACEPTADO' as const,
      estado: 'EN_CONTROL_CALIDAD' as const,
      observaciones: 'En proceso de control de calidad final.',
      activo: true,
      created_by: admin.id,
    },
  ];

  const recepciones = [];
  for (const data of recepcionesData) {
    const r = await prisma.recepciones.create({ data });
    recepciones.push(r);
  }
  console.log(`✅ ${recepciones.length} recepciones creadas`);

  // ─── PROCESAMIENTOS ───────────────────────────────────────
  const procesamientosData = [
    {
      codigo: 'OP-001',
      campania_id: campanias[0].id,
      fecha: new Date('2025-03-20'),
      producto: 'Quinua Real Orgánica',
      responsable: 'Ing. Carlos Mendoza',
      planta: 'Planta Procesadora San Juan',
      linea_procesamiento: 'GRANOS' as const,
      estado: 'COMPLETADA' as const,
      peso_entrada: 4275,
      peso_salida: 4100,
      merma: 175,
      rendimiento: 95.9,
      producto_base: 'Quinua pelada',
      calidad_producto: 'PRIMERA' as const,
      observaciones: 'Proceso de pelado y selección completado exitosamente.',
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'OP-002',
      campania_id: campanias[0].id,
      fecha: new Date('2025-04-01'),
      producto: 'Quinua Orgánica Premium',
      responsable: 'Ing. María García',
      planta: 'Planta Procesadora San Juan',
      linea_procesamiento: 'GRANOS' as const,
      estado: 'EN_PROCESO' as const,
      peso_entrada: 2790,
      peso_salida: null,
      merma: null,
      rendimiento: null,
      producto_base: 'Quinua lavada y deshidratada',
      calidad_producto: 'PRIMERA' as const,
      observaciones: 'En proceso de lavado y deshidratación.',
      activo: true,
      created_by: admin.id,
    },
    {
      codigo: 'OP-003',
      campania_id: campanias[1].id,
      fecha: new Date('2025-04-15'),
      producto: 'Papa Nativa Procesada',
      responsable: 'Ing. Carlos Mendoza',
      planta: 'Planta Procesadora Chuschi',
      linea_procesamiento: 'TUBERCULOS' as const,
      estado: 'REGISTRADA' as const,
      peso_entrada: 1350,
      peso_salida: null,
      merma: null,
      rendimiento: null,
      producto_base: 'Papa seca',
      calidad_producto: 'SEGUNDA' as const,
      observaciones: 'Procesamiento registrado, pendiente de inicio.',
      activo: true,
      created_by: admin.id,
    },
  ];

  const procesamientos = [];
  for (const data of procesamientosData) {
    const p = await prisma.procesamientos.create({ data });
    procesamientos.push(p);
  }
  console.log(`✅ ${procesamientos.length} procesamientos creados`);

  // ─── RESUMEN ────────────────────────────────────────────────
  console.log('\n📊 Resumen del seed:');
  console.log(`   👤 Usuarios:      3 (admin, 2 técnicos)`);
  console.log(`   👨‍🌾 Productores:    ${productores.length}`);
  console.log(`   👪 Familiares:     ${cleanedFamiliares.length}`);
  console.log(`   🌾 Parcelas:      ${parcelas.length}`);
  console.log(`   📅 Campañas:      ${campanias.length}`);
  console.log(`   🌱 Cultivos:      ${cultivos.length}`);
  console.log(`   📋 Actividades:   ${actividades.length}`);
  console.log(`   🔍 Inspecciones:  ${inspecciones.length}`);
  console.log(`   🚛 Acopios:       ${acopios.length}`);
  console.log(`   📥 Recepciones:   ${recepciones.length}`);
  console.log(`   ⚙️  Procesamientos: ${procesamientos.length}`);
  console.log(`   📦 Lotes:         ${lotes.length}`);
  console.log(`   🏪 Inventario:    ${inventarioItems.length}`);
  console.log(`   🔗 Trazabilidad:  ${trazabilidades.length}`);

  const org = parcelas.filter(p => p.certificacion === 'ORGANICA').length;
  const trans = parcelas.filter(p => p.certificacion === 'EN_TRANSICION').length;
  const conv = parcelas.filter(p => p.certificacion === 'CONVENCIONAL').length;
  console.log(`\n   🌿 Certificación:`);
  console.log(`      Orgánica:       ${org} parcelas`);
  console.log(`      En transición:  ${trans} parcelas`);
  console.log(`      Convencional:   ${conv} parcelas`);

  const totalArea = parcelas.reduce((sum, p) => sum + Number(p.area), 0);
  const areaCert = parcelas.filter(p => p.certificacion === 'ORGANICA').reduce((sum, p) => sum + Number(p.area), 0);
  console.log(`\n   📐 Superficie total: ${totalArea} ha`);
  console.log(`   ✅ Área certificada: ${areaCert} ha (${((areaCert / totalArea) * 100).toFixed(1)}%)`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
    console.log('\n🎉 Seed completado exitosamente.');
  })
  .catch(async (e) => {
    console.error('❌ Error en seed:', e);
    await prisma.$disconnect();
    process.exit(1);
  });
